// GENERATED by tools/measmod_reference.cpp — do not edit; `measmod_reference --check` verifies it.
// Reference values computed independently of the code under test (see the generator's header).
#pragma once

namespace odl::measmod::ref {

// section: registry
inline constexpr double yarl_elapsed_years = 11.000927789204093;
inline constexpr double yarl_marker_x_m = -2389008.285157414;
inline constexpr double yarl_marker_y_m = 5043329.573492286;
inline constexpr double yarl_marker_z_m = -3078523.410273481;
inline constexpr double yarl_marker_lat_rad = -0.5069567680129888;
inline constexpr double yarl_marker_lon_rad = 2.013180703304968;
inline constexpr double yarl_marker_h_m = 241.32091017680722;
inline constexpr double yarl_srp_x_m = -2389009.492492338;
inline constexpr double yarl_srp_y_m = 5043332.076926578;
inline constexpr double yarl_srp_z_m = -3078524.9611299336;
inline constexpr double yarl_srp_lat_rad = -0.50695676902075;
inline constexpr double yarl_srp_lon_rad = 2.013180706781326;
inline constexpr double yarl_srp_h_m = 244.5036101766431;
inline constexpr double yarl_srp_minus_marker_m = 3.1827655600122355;

// section: shapiro
inline constexpr double shapiro_two_gm_over_c2_m = 0.008870056071559442;
inline constexpr double shapiro_zenith_r1_m = 6378137.0;
inline constexpr double shapiro_zenith_r2_m = 12270000.0;
inline constexpr double shapiro_zenith_rho_m = 5891863.0;
inline constexpr double shapiro_zenith_delay_m = 0.005803511021732269;
inline constexpr double shapiro_zenith_d_rho = 1.0568014839281048e-09;
inline constexpr double shapiro_zenith_d_r = -3.3389552862578685e-10;
inline constexpr double shapiro_el10_r1_m = 6378137.0;
inline constexpr double shapiro_el10_r2_m = 12270000.0;
inline constexpr double shapiro_el10_rho_m = 9432796.30315455;
inline constexpr double shapiro_el10_delay_m = 0.009883204994431896;
inline constexpr double shapiro_el10_d_rho = 1.2784062288058797e-09;
inline constexpr double shapiro_el10_d_r = -6.466568509771165e-10;
inline constexpr double shapiro_leo30_r1_m = 6378137.0;
inline constexpr double shapiro_leo30_r2_m = 7400000.0;
inline constexpr double shapiro_leo30_rho_m = 1735312.3044182826;
inline constexpr double shapiro_leo30_delay_m = 0.002246238125552409;
inline constexpr double shapiro_leo30_d_rho = 1.3083083835284128e-09;
inline constexpr double shapiro_leo30_d_r = -1.6477725805095772e-10;

// section: vapour
inline constexpr double vapour_a_t_c = 20.0;
inline constexpr double vapour_a_rh = 0.5;
inline constexpr double vapour_a_e_hpa = 11.694678421549668;
inline constexpr double vapour_b_t_c = 0.0;
inline constexpr double vapour_b_rh = 1.0;
inline constexpr double vapour_b_e_hpa = 6.11;
inline constexpr double vapour_c_t_c = -10.0;
inline constexpr double vapour_c_rh = 0.3;
inline constexpr double vapour_c_e_hpa = 0.8574366841438029;
inline constexpr double vapour_d_t_c = 35.0;
inline constexpr double vapour_d_rh = 0.8;
inline constexpr double vapour_d_e_hpa = 44.992640343968546;

// section: zenith
inline constexpr double zenith_lat_rad = 0.535321570465705;
inline constexpr double zenith_height_m = 2010.344;
inline constexpr double zenith_p_hpa = 798.4188;
inline constexpr double zenith_e_hpa = 14.322;
inline constexpr double zenith_lambda_um = 0.532;
inline constexpr double zenith_hydrostatic_m = 1.9329959722362897;
inline constexpr double zenith_wet_m = 0.002233752731683583;
inline constexpr double zenith_total_m = 1.9352297249679733;

// section: np
inline constexpr double np_first_tof_s = 0.051212898595;
inline constexpr double np_first_observed_range_m = 7676620.3755498985;

// section: lighttime
inline constexpr double lt_lageos_s0_x = 4000000.0;
inline constexpr double lt_lageos_s0_y = 3100000.0;
inline constexpr double lt_lageos_s0_z = 3900000.0;
inline constexpr double lt_lageos_vs_x = -250.0;
inline constexpr double lt_lageos_vs_y = 380.0;
inline constexpr double lt_lageos_vs_z = 0.0;
inline constexpr double lt_lageos_r0_x = 9000000.0;
inline constexpr double lt_lageos_r0_y = 5000000.0;
inline constexpr double lt_lageos_r0_z = 6000000.0;
inline constexpr double lt_lageos_vr_x = -3000.0;
inline constexpr double lt_lageos_vr_y = 4500.0;
inline constexpr double lt_lageos_vr_z = 2800.0;
inline constexpr double lt_lageos_e2_tau_u_s = 0.019167597802924468;
inline constexpr double lt_lageos_e2_tau_d_s = 0.019167609551548028;
inline constexpr double lt_lageos_e2_tof_s = 0.038335207354472496;
inline constexpr double lt_lageos_e2_range_m = 5746303.020368493;
inline constexpr double lt_lageos_e2_d_range_dx = 0.8701154727303599;
inline constexpr double lt_lageos_e2_d_range_dy = 0.33066110821683625;
inline constexpr double lt_lageos_e2_d_range_dz = 0.3654616910022405;
inline constexpr double lt_lageos_e1_tau_u_s = 0.019167598266304344;
inline constexpr double lt_lageos_e1_tau_d_s = 0.019167610015888938;
inline constexpr double lt_lageos_e1_tof_s = 0.03833520828219328;
inline constexpr double lt_lageos_e1_range_m = 5746303.159430341;
inline constexpr double lt_lageos_e1_d_range_dx = 0.8701246455832055;
inline constexpr double lt_lageos_e1_d_range_dy = 0.3306473653211325;
inline constexpr double lt_lageos_e1_d_range_dz = 0.3654523511448389;
inline constexpr double lt_leo_s0_x = 6000000.0;
inline constexpr double lt_leo_s0_y = -1500000.0;
inline constexpr double lt_leo_s0_z = 1900000.0;
inline constexpr double lt_leo_vs_x = 180.0;
inline constexpr double lt_leo_vs_y = 440.0;
inline constexpr double lt_leo_vs_z = 0.0;
inline constexpr double lt_leo_r0_x = 7000000.0;
inline constexpr double lt_leo_r0_y = -700000.0;
inline constexpr double lt_leo_r0_z = 2400000.0;
inline constexpr double lt_leo_vr_x = 2000.0;
inline constexpr double lt_leo_vr_y = 6500.0;
inline constexpr double lt_leo_vr_z = 3000.0;
inline constexpr double lt_leo_e2_tau_u_s = 0.0045858449490811;
inline constexpr double lt_leo_e2_tau_d_s = 0.004585833110178969;
inline constexpr double lt_leo_e2_tof_s = 0.00917167805926007;
inline constexpr double lt_leo_e2_range_m = 1374799.954685123;
inline constexpr double lt_leo_e2_d_range_dx = 0.7273990384979561;
inline constexpr double lt_leo_e2_d_range_dy = 0.5819345884343363;
inline constexpr double lt_leo_e2_d_range_dz = 0.36370649087939566;
inline constexpr double lt_leo_e1_tau_u_s = 0.004585754065402847;
inline constexpr double lt_leo_e1_tau_d_s = 0.00458574222680625;
inline constexpr double lt_leo_e1_tof_s = 0.009171496292209098;
inline constexpr double lt_leo_e1_range_m = 1374772.7084896257;
inline constexpr double lt_leo_e1_d_range_dx = 0.7273929674543915;
inline constexpr double lt_leo_e1_d_range_dy = 0.5819143739647877;
inline constexpr double lt_leo_e1_d_range_dz = 0.36369648372680824;

// section: position
inline constexpr double position_horizons_x_km = 7049.479204680989;
inline constexpr double position_horizons_x_m = 7049479.204680989;
inline constexpr double position_horizons_y_km = -1823.447981968663;
inline constexpr double position_horizons_y_m = -1823447.981968663;
inline constexpr double position_horizons_z_km = 760.5020081570782;
inline constexpr double position_horizons_z_m = 760502.0081570782;
inline constexpr double position_horizons_norm_km = 7321.098476634927;
inline constexpr double position_sp3_x_km = -11319.687869;
inline constexpr double position_sp3_x_m = -11319687.869;
inline constexpr double position_sp3_y_km = -4845.099064;
inline constexpr double position_sp3_y_m = -4845099.064;
inline constexpr double position_sp3_z_km = -497.695158;
inline constexpr double position_sp3_z_m = -497695.158;
inline constexpr double position_sp3_norm_km = 12323.06856516899;

// section: aberration
inline constexpr double ab_annual_n_x = 0.6;
inline constexpr double ab_annual_beta_x = 0.0;
inline constexpr double ab_annual_a_x = 0.5999999970597;
inline constexpr double ab_annual_d_x = 0.5999999970597;
inline constexpr double ab_annual_n_y = 0.0;
inline constexpr double ab_annual_beta_y = 9.9e-05;
inline constexpr double ab_annual_a_y = 9.9e-05;
inline constexpr double ab_annual_d_y = -9.9e-05;
inline constexpr double ab_annual_n_z = 0.8;
inline constexpr double ab_annual_beta_z = 0.0;
inline constexpr double ab_annual_a_z = 0.7999999960796;
inline constexpr double ab_annual_d_z = 0.7999999960796;
inline constexpr double ab_oblique_n_x = 0.48;
inline constexpr double ab_oblique_beta_x = 7e-05;
inline constexpr double ab_oblique_a_x = 0.48002718253731763;
inline constexpr double ab_oblique_d_x = 0.4799728145370567;
inline constexpr double ab_oblique_n_y = -0.6;
inline constexpr double ab_oblique_beta_y = -5e-05;
inline constexpr double ab_oblique_a_y = -0.5999964798439978;
inline constexpr double ab_oblique_d_y = -0.60000351984397;
inline constexpr double ab_oblique_n_z = 0.64;
inline constexpr double ab_oblique_beta_z = 4e-05;
inline constexpr double ab_oblique_a_z = 0.6399829124282114;
inline constexpr double ab_oblique_d_z = 0.6400170884282879;
inline constexpr double ab_large_n_x = -0.36;
inline constexpr double ab_large_beta_x = 0.0003;
inline constexpr double ab_large_a_x = -0.35966392860712615;
inline constexpr double ab_large_d_x = -0.36033592859284613;
inline constexpr double ab_large_n_y = 0.48;
inline constexpr double ab_large_beta_y = -0.0004;
inline constexpr double ab_large_a_y = 0.47955190480950155;
inline constexpr double ab_large_d_y = 0.4804479047904615;
inline constexpr double ab_large_n_z = 0.8;
inline constexpr double ab_large_beta_z = 0.0005;
inline constexpr double ab_large_a_z = 0.800419783021676;
inline constexpr double ab_large_d_z = 0.799579782978276;
inline constexpr double ab_diurnal_n_x = 0.0;
inline constexpr double ab_diurnal_beta_x = 0.0;
inline constexpr double ab_diurnal_a_x = 0.0;
inline constexpr double ab_diurnal_d_x = 0.0;
inline constexpr double ab_diurnal_n_y = 0.6;
inline constexpr double ab_diurnal_beta_y = 1.55e-06;
inline constexpr double ab_diurnal_a_y = 0.6000009919990774;
inline constexpr double ab_diurnal_d_y = 0.5999990079990775;
inline constexpr double ab_diurnal_n_z = 0.8;
inline constexpr double ab_diurnal_beta_z = 0.0;
inline constexpr double ab_diurnal_a_z = 0.799999255999731;
inline constexpr double ab_diurnal_d_z = 0.800000743999731;

// section: emission
inline constexpr double em_lageos_tau_s = 0.01916761048713511;
inline constexpr double em_lageos_rho_m = 5746305.061924812;
inline constexpr double em_lageos_n_x = 0.8701343644217552;
inline constexpr double em_lageos_n_y = 0.3306322454652978;
inline constexpr double em_lageos_n_z = 0.36544289035487215;
inline constexpr double em_leo_tau_s = 0.004585651347971228;
inline constexpr double em_leo_rho_m = 1374743.6891393077;
inline constexpr double em_leo_n_x = 0.7274016506476004;
inline constexpr double em_leo_n_y = 0.5819049758774156;
inline constexpr double em_leo_n_z = 0.36369415404189626;

}  // namespace odl::measmod::ref
