// GENERATED by tools/measmod_reference.py — do not edit; `python3 tools/measmod_reference.py --check` verifies it.
// Reference values computed independently of the code under test (see the generator's header).
#pragma once

namespace odl::measmod::ref {

// section: registry
inline constexpr double yarl_elapsed_years = 11.000927789204093;
inline constexpr double yarl_marker_x_m = -2389008.285157414;
inline constexpr double yarl_marker_y_m = 5043329.573492286;
inline constexpr double yarl_marker_z_m = -3078523.410273481;
inline constexpr double yarl_marker_lat_rad = -0.5069567680129888;
inline constexpr double yarl_marker_lon_rad = 2.013180703304968;
inline constexpr double yarl_marker_h_m = 241.32091017680722;
inline constexpr double yarl_srp_x_m = -2389009.492492338;
inline constexpr double yarl_srp_y_m = 5043332.076926578;
inline constexpr double yarl_srp_z_m = -3078524.9611299336;
inline constexpr double yarl_srp_lat_rad = -0.50695676902075;
inline constexpr double yarl_srp_lon_rad = 2.013180706781326;
inline constexpr double yarl_srp_h_m = 244.5036101766431;
inline constexpr double yarl_srp_minus_marker_m = 3.1827655600122355;

// section: shapiro
inline constexpr double shapiro_two_gm_over_c2_m = 0.008870056071559442;
inline constexpr double shapiro_zenith_r1_m = 6378137.0;
inline constexpr double shapiro_zenith_r2_m = 12270000.0;
inline constexpr double shapiro_zenith_rho_m = 5891863.0;
inline constexpr double shapiro_zenith_delay_m = 0.005803511021732269;
inline constexpr double shapiro_zenith_d_rho = 1.0568014839281048e-09;
inline constexpr double shapiro_zenith_d_r = -3.3389552862578685e-10;
inline constexpr double shapiro_el10_r1_m = 6378137.0;
inline constexpr double shapiro_el10_r2_m = 12270000.0;
inline constexpr double shapiro_el10_rho_m = 9432796.30315455;
inline constexpr double shapiro_el10_delay_m = 0.009883204994431896;
inline constexpr double shapiro_el10_d_rho = 1.2784062288058797e-09;
inline constexpr double shapiro_el10_d_r = -6.466568509771165e-10;
inline constexpr double shapiro_leo30_r1_m = 6378137.0;
inline constexpr double shapiro_leo30_r2_m = 7400000.0;
inline constexpr double shapiro_leo30_rho_m = 1735312.3044182826;
inline constexpr double shapiro_leo30_delay_m = 0.002246238125552409;
inline constexpr double shapiro_leo30_d_rho = 1.3083083835284128e-09;
inline constexpr double shapiro_leo30_d_r = -1.6477725805095772e-10;

// section: vapour
inline constexpr double vapour_a_t_c = 20.0;
inline constexpr double vapour_a_rh = 0.5;
inline constexpr double vapour_a_e_hpa = 11.694678421549668;
inline constexpr double vapour_b_t_c = 0.0;
inline constexpr double vapour_b_rh = 1.0;
inline constexpr double vapour_b_e_hpa = 6.11;
inline constexpr double vapour_c_t_c = -10.0;
inline constexpr double vapour_c_rh = 0.3;
inline constexpr double vapour_c_e_hpa = 0.8574366841438029;
inline constexpr double vapour_d_t_c = 35.0;
inline constexpr double vapour_d_rh = 0.8;
inline constexpr double vapour_d_e_hpa = 44.992640343968546;

// section: zenith
inline constexpr double zenith_lat_rad = 0.535321570465705;
inline constexpr double zenith_height_m = 2010.344;
inline constexpr double zenith_p_hpa = 798.4188;
inline constexpr double zenith_e_hpa = 14.322;
inline constexpr double zenith_lambda_um = 0.532;
inline constexpr double zenith_hydrostatic_m = 1.9329959722362897;
inline constexpr double zenith_wet_m = 0.002233752731683583;
inline constexpr double zenith_total_m = 1.9352297249679733;

}  // namespace odl::measmod::ref
