// GENERATED by tools/forcemodel_comparator_header.cpp — do not edit.
//
// The extended-precision comparator's data (SPEC-forcemodel.md §6.2 (e)): for each coefficient (n, m, kind) of degrees 2 – 4 the exact
// harmonic polynomial q, whose potential is GM a_e^n N_nm q / r^(2n+1), with N_nm and the registered bound's Phi_nm.  Each monomial
// coefficient is a dyadic rational, exact in a double; N_nm is printed to 24 digits for a long double.
#pragma once

namespace odl::forcemodel::comparator {

struct Monomial { int i, j, k; double c; };
struct Harmonic {
    int n, m;
    char kind;                 ///< 'C' or 'S'
    long double norm;          ///< N_nm, TN36-6 (6.2b)
    double phi;                ///< Lemma 2's Phi_nm (tools/forcemodel_fd_sizing.cpp)
    const Monomial* q;
    int terms;
};

inline constexpr Monomial kQ_2_0_C[] = {
    {0, 0, 2, 0x1.0000000000000p+0},
    {0, 2, 0, -0x1.0000000000000p-1},
    {2, 0, 0, -0x1.0000000000000p-1},
};
inline constexpr Monomial kQ_2_1_C[] = {
    {1, 0, 1, 0x1.8000000000000p+1},
};
inline constexpr Monomial kQ_2_1_S[] = {
    {0, 1, 1, 0x1.8000000000000p+1},
};
inline constexpr Monomial kQ_2_2_C[] = {
    {0, 2, 0, -0x1.8000000000000p+1},
    {2, 0, 0, 0x1.8000000000000p+1},
};
inline constexpr Monomial kQ_2_2_S[] = {
    {1, 1, 0, 0x1.8000000000000p+2},
};
inline constexpr Monomial kQ_3_0_C[] = {
    {0, 0, 3, 0x1.0000000000000p+0},
    {0, 2, 1, -0x1.8000000000000p+0},
    {2, 0, 1, -0x1.8000000000000p+0},
};
inline constexpr Monomial kQ_3_1_C[] = {
    {1, 0, 2, 0x1.8000000000000p+2},
    {1, 2, 0, -0x1.8000000000000p+0},
    {3, 0, 0, -0x1.8000000000000p+0},
};
inline constexpr Monomial kQ_3_1_S[] = {
    {0, 1, 2, 0x1.8000000000000p+2},
    {0, 3, 0, -0x1.8000000000000p+0},
    {2, 1, 0, -0x1.8000000000000p+0},
};
inline constexpr Monomial kQ_3_2_C[] = {
    {0, 2, 1, -0x1.e000000000000p+3},
    {2, 0, 1, 0x1.e000000000000p+3},
};
inline constexpr Monomial kQ_3_2_S[] = {
    {1, 1, 1, 0x1.e000000000000p+4},
};
inline constexpr Monomial kQ_3_3_C[] = {
    {1, 2, 0, -0x1.6800000000000p+5},
    {3, 0, 0, 0x1.e000000000000p+3},
};
inline constexpr Monomial kQ_3_3_S[] = {
    {0, 3, 0, -0x1.e000000000000p+3},
    {2, 1, 0, 0x1.6800000000000p+5},
};
inline constexpr Monomial kQ_4_0_C[] = {
    {0, 0, 4, 0x1.0000000000000p+0},
    {0, 2, 2, -0x1.8000000000000p+1},
    {0, 4, 0, 0x1.8000000000000p-2},
    {2, 0, 2, -0x1.8000000000000p+1},
    {2, 2, 0, 0x1.8000000000000p-1},
    {4, 0, 0, 0x1.8000000000000p-2},
};
inline constexpr Monomial kQ_4_1_C[] = {
    {1, 0, 3, 0x1.4000000000000p+3},
    {1, 2, 1, -0x1.e000000000000p+2},
    {3, 0, 1, -0x1.e000000000000p+2},
};
inline constexpr Monomial kQ_4_1_S[] = {
    {0, 1, 3, 0x1.4000000000000p+3},
    {0, 3, 1, -0x1.e000000000000p+2},
    {2, 1, 1, -0x1.e000000000000p+2},
};
inline constexpr Monomial kQ_4_2_C[] = {
    {0, 2, 2, -0x1.6800000000000p+5},
    {0, 4, 0, 0x1.e000000000000p+2},
    {2, 0, 2, 0x1.6800000000000p+5},
    {4, 0, 0, -0x1.e000000000000p+2},
};
inline constexpr Monomial kQ_4_2_S[] = {
    {1, 1, 2, 0x1.6800000000000p+6},
    {1, 3, 0, -0x1.e000000000000p+3},
    {3, 1, 0, -0x1.e000000000000p+3},
};
inline constexpr Monomial kQ_4_3_C[] = {
    {1, 2, 1, -0x1.3b00000000000p+8},
    {3, 0, 1, 0x1.a400000000000p+6},
};
inline constexpr Monomial kQ_4_3_S[] = {
    {0, 3, 1, -0x1.a400000000000p+6},
    {2, 1, 1, 0x1.3b00000000000p+8},
};
inline constexpr Monomial kQ_4_4_C[] = {
    {0, 4, 0, 0x1.a400000000000p+6},
    {2, 2, 0, -0x1.3b00000000000p+9},
    {4, 0, 0, 0x1.a400000000000p+6},
};
inline constexpr Monomial kQ_4_4_S[] = {
    {1, 3, 0, -0x1.a400000000000p+8},
    {3, 1, 0, 0x1.a400000000000p+8},
};

inline constexpr Harmonic kHarmonics[] = {
    {2, 0, 'C', 2.236067977499789696409174L, 0x1.a343434eb9762p+14, kQ_2_0_C, 3},
    {2, 1, 'C', 1.290994448735805628393088L, 0x1.6b1799add9640p+14, kQ_2_1_C, 1},
    {2, 1, 'S', 1.290994448735805628393088L, 0x1.6b1799add9640p+14, kQ_2_1_S, 1},
    {2, 2, 'C', 0.645497224367902814196544L, 0x1.6b1799add9640p+14, kQ_2_2_C, 2},
    {2, 2, 'S', 0.645497224367902814196544L, 0x1.6b1799add9640p+14, kQ_2_2_S, 1},
    {3, 0, 'C', 2.645751311064590590501616L, 0x1.7934a1a03c0c8p+17, kQ_3_0_C, 3},
    {3, 1, 'C', 1.080123449734643371827661L, 0x1.57b1c6adf604ap+17, kQ_3_1_C, 3},
    {3, 1, 'S', 1.080123449734643371827661L, 0x1.57b1c6adf604ap+17, kQ_3_1_S, 3},
    {3, 2, 'C', 0.341565025531986612774035L, 0x1.6466d980b401dp+17, kQ_3_2_C, 2},
    {3, 2, 'S', 0.341565025531986612774035L, 0x1.6466d980b401dp+17, kQ_3_2_S, 1},
    {3, 3, 'C', 0.139443337755679257996362L, 0x1.2a350b4b85410p+17, kQ_3_3_C, 2},
    {3, 3, 'S', 0.139443337755679257996362L, 0x1.2a350b4b85410p+17, kQ_3_3_S, 2},
    {4, 0, 'C', 3.000000000000000000000000L, 0x1.0e7e000000000p+20, kQ_4_0_C, 6},
    {4, 1, 'C', 0.948683298050513799599668L, 0x1.f54863c52af9dp+19, kQ_4_1_C, 3},
    {4, 1, 'S', 0.948683298050513799599668L, 0x1.f54863c52af9dp+19, kQ_4_1_S, 3},
    {4, 2, 'C', 0.223606797749978969640917L, 0x1.ee4f8f197cf68p+19, kQ_4_2_C, 4},
    {4, 2, 'S', 0.223606797749978969640917L, 0x1.17b35e681230ap+20, kQ_4_2_S, 3},
    {4, 3, 'C', 0.059761430466719681998441L, 0x1.05a2d1843f56ap+20, kQ_4_3_C, 2},
    {4, 3, 'S', 0.059761430466719681998441L, 0x1.05a2d1843f56ap+20, kQ_4_3_S, 2},
    {4, 4, 'C', 0.021128856368212914437740L, 0x1.7a8963086a8f0p+19, kQ_4_4_C, 3},
    {4, 4, 'S', 0.021128856368212914437740L, 0x1.7a8963086a8f0p+19, kQ_4_4_S, 2},
};

}  // namespace odl::forcemodel::comparator
