#pragma once
// odl/io/sgp4.hpp — this tree's own port of SGP4/SDP4, TEME output.
//
// SPEC-io-sgp4.md. Ported from Hoots & Roehrich (1980), Spacetrack Report
// No. 3 (`STR3`), sections 6/7/10/11 — equations AND their own FORTRAN IV
// listing together, ruled normative (manager, plan/subplan_L6/L6-3.md,
// 2026-09-29): STR3's FORTRAN is a public-domain 1980 government report's
// OWN specification, not a secondary implementation of laws published
// elsewhere the way `eclips.f` was, and there is no equations-only edition
// to prefer instead. Corrections from Vallado, Crawford, Hujsak & Kelso
// (2006), `VAL06`, applied where its own prose describes one -- each
// recorded in PROVENANCE.md with its location in the paper. Vallado's own
// 2006 reference CODE (the archive's `sgp4/cpp` etc., and the source
// reprinted in VAL06's own appendix) stays unopened throughout: the
// published verification vectors were generated BY that code, so reading it
// would make the vectors test agreement with an implementation, bugs
// included, rather than testing whether the corrections were applied
// correctly (D4).
//
// TEME is SGP4's own, and only, output frame (STR3 never names another).
// This module returns a raw TEME position/velocity; converting onward to
// GCRS is `odl::frames::to_gcrs(const TemeState&, ...)`, L1's own function
// (FRAME-R-030) -- this module never assumes an inertial frame and performs
// no frame rotation of its own beyond what STR3's own equations already are.

#include <odl/core/result.hpp>
#include <odl/frames/state.hpp>
#include <odl/io/tle.hpp>
#include <odl/time/epoch.hpp>
#include <odl/time/leap_table.hpp>

namespace odl::io {

using Sgp4Error = odl::Diagnostic;

/// The TLE's own epoch, as a calendar date -- built from `Tle::epoch_year`/
/// `epoch_day`, never from a format reader (readers return raw fields, per
/// every other reader in this tree; `Tle` carries none of the pivot-year
/// decision below).
///
/// THE TWO-DIGIT YEAR PIVOT IS NOT PART OF SGP4'S OWN MATHEMATICAL
/// DEFINITION (`VAL06` §II.E: "only peripherally related to SGP4... If the
/// year is less than 50, 57, or some other value, one can add 2000,
/// otherwise 1900... these are only temporary fixes" -- VAL06 itself names
/// no single settled value). This tree pivots at 57: no real TLE epoch can
/// predate Sputnik 1 (1957), so 00-56 -> 2000-2056 and 57-99 -> 1957-1999
/// is unambiguous for every physically possible epoch, the same reasoning
/// CelesTrak's own current TLE generation and every other maintained SGP4
/// port uses (57 is one of VAL06's own two named options, and the one with
/// a physical justification the other lacks).
[[nodiscard]] time::Calendar tle_epoch_calendar(const Tle& tle);

/// Everything SGP4/SDP4 compute ONCE from a TLE's own osculating elements --
/// the FORTRAN's own `IFLAG=0` initialization branch, returned as a value
/// instead of left in a COMMON block (no global state; a caller propagating
/// the same TLE to many epochs computes this once and reuses it). Every
/// field is an internal coefficient with no meaning outside
/// `sgp4_propagate` -- named after STR3's own FORTRAN variables (§6/§7/§10)
/// so the port is checkable line by line against the source, not because
/// any of them is meant to be read by a caller.
struct Sgp4InitialState {
    bool deep_space = false;

    // -- recovered mean motion / semimajor axis (STR3 §6/§7's shared first
    //    step; §11's own dispatch: period >= 225 min -> deep_space) --
    double xnodp = 0.0, aodp = 0.0;
    double eo = 0.0;  ///< the TLE's own epoch eccentricity, needed again (near-earth's own `E=EO-TEMPE`)

    double bstar = 0.0;  ///< the TLE's own drag term, needed again at every propagate call

    // -- STR3 §6/§7's shared perturbation-coefficient block --
    double cosio = 0.0, sinio = 0.0, theta2 = 0.0, x3thm1 = 0.0, x1mth2 = 0.0, x7thm1 = 0.0;
    double betao = 0.0, betao2 = 0.0;
    double c1 = 0.0, c2 = 0.0, c3 = 0.0, c4 = 0.0, c5 = 0.0;
    double omgdot = 0.0, xmdot = 0.0, xnodot = 0.0, xnodcf = 0.0;
    double a3ovk2 = 0.0, xlcof = 0.0, aycof = 0.0;

    // -- near-earth only (STR3 §6): the ISIMP-gated secular-truncation and
    //    long-period terms; never populated for a deep-space orbit --
    bool isimp = false;
    double eta = 0.0;  ///< STR3 §6's own ETA = aodp*eo*tsi, needed again for XMCOF's own delta-M term.
    double t2cof = 0.0, t3cof = 0.0, t4cof = 0.0, t5cof = 0.0;
    double omgcof = 0.0, xmcof = 0.0, delmo = 0.0, sinmo = 0.0;
    double d2 = 0.0, d3 = 0.0, d4 = 0.0;

    // -- deep-space only (STR3 §10 `DPINIT`, both the lunar-solar common
    //    terms and, when resonant, the geopotential-resonance terms) --
    double xnodeo_saved = 0.0, omegao_saved = 0.0, xmo_saved = 0.0, xincl_saved = 0.0;
    double eq = 0.0, xqncl = 0.0, aqnv = 0.0, xmao = 0.0, xpidot = 0.0;
    double thgr = 0.0;
    double sse = 0.0, ssi = 0.0, ssl = 0.0, ssh = 0.0, ssg = 0.0;
    // STR3 §10's own SE2/SI2/.../SH3/SL4/SGH4: the SOLAR term block's raw
    // EE2/XI2/.../XH3/XL4/XGH4, saved under these names before the lunar
    // term block (same formulas, different inputs) overwrites the raw
    // names. `DPPER` uses these renamed (solar) fields for its own
    // "S..." (SES/SIS/SLS/SGHS/SHS) quantities.
    double se2 = 0.0, si2 = 0.0, sl2 = 0.0, sgh2 = 0.0, sh2 = 0.0;
    double se3 = 0.0, si3 = 0.0, sl3 = 0.0, sgh3 = 0.0, sh3 = 0.0;
    double sl4 = 0.0, sgh4 = 0.0;
    // The LUNAR term block's own raw EE2/E3/XI2/XI3/XL2/XL3/XL4/XGH2/XGH3/
    // XGH4/XH2/XH3 -- STR3's own DPPER reads these names DIRECTLY,
    // unrenamed, for its "L..." (SEL/SIL/SLL/SGHL/SHL) quantities. A
    // SEPARATE set of fields from se2/si2/... above on purpose: STR3's own
    // FORTRAN reuses EE2/E3/etc for both the solar and lunar term-block
    // calls (renaming the SOLAR result to SE2/SI2/... immediately after,
    // before the lunar call overwrites EE2/E3/... itself), and folding the
    // two into one field each, as an earlier draft of this port did, is
    // exactly the kind of FORTRAN-variable-reuse trap that produces a wrong
    // DPPER with no compiler warning.
    double lun_ee2 = 0.0, lun_e3 = 0.0, lun_xi2 = 0.0, lun_xi3 = 0.0;
    double lun_xl2 = 0.0, lun_xl3 = 0.0, lun_xl4 = 0.0;
    double lun_xgh2 = 0.0, lun_xgh3 = 0.0, lun_xgh4 = 0.0, lun_xh2 = 0.0, lun_xh3 = 0.0;
    double zmol = 0.0, zmos = 0.0;
    bool iresfl = false, isynfl = false;
    double d2201 = 0.0, d2211 = 0.0, d3210 = 0.0, d3222 = 0.0;
    double d4410 = 0.0, d4422 = 0.0, d5220 = 0.0, d5232 = 0.0, d5421 = 0.0, d5433 = 0.0;
    double del1 = 0.0, del2 = 0.0, del3 = 0.0, fasx2 = 0.0, fasx4 = 0.0, fasx6 = 0.0;
    double xlamo = 0.0, xfact = 0.0, omgdt_saved = 0.0;
};

/// Builds `Sgp4InitialState` from a TLE (STR3 §6/§7's own initialization
/// equations, and, when the orbit is deep-space, §10's `DPINIT`). Refuses
/// (`IOSG-F-001`) an inclination within a small tolerance of 180 degrees --
/// `1/sin(i)` and `1/(1+cos(i))` terms are undefined there, `VAL06` §VI.A's
/// own named fix.
[[nodiscard]] odl::Result<Sgp4InitialState, Sgp4Error> sgp4_init(const Tle& tle);

/// Whether `sgp4_init` classified this TLE as a deep-space (SDP4) orbit --
/// STR3 §11's own dispatch: period >= 225 minutes, i.e. mean motion below a
/// fixed threshold once the initial mean-motion recovery (§6/§7's shared
/// first step) has been applied. Exposed for callers who report which path
/// a case took (T-01's own gate design, "the case's features").
[[nodiscard]] bool sgp4_is_deep_space(const Sgp4InitialState& state) noexcept;

/// A raw SGP4/SDP4 output: position (km) and velocity (km/s), still in
/// TEME, still carrying no epoch of its own -- the caller pairs it with the
/// `time::Epoch` it asked for. Separated from `frames::TemeState` only so a
/// caller can get the numbers without also supplying an `Epoch` up front;
/// `propagate_teme`, below, is the ergonomic entry point that returns the
/// typed state directly.
struct Sgp4RawState {
    double x_km = 0.0, y_km = 0.0, z_km = 0.0;
    double xdot_km_s = 0.0, ydot_km_s = 0.0, zdot_km_s = 0.0;
};

/// Propagates to `tsince_minutes` since the TLE's own epoch (STR3's own
/// TSINCE, the algorithm's native input) and returns the raw TEME state in
/// km/km-s (STR3 §11's own final AE->km, AE/min->km/s conversion applied
/// here, once, rather than left to the caller). `tsince_minutes` may be
/// negative (STR3 imposes no forward-only restriction, and `VAL06` §VI.D's
/// own integrator fix is specifically about backward propagation being
/// reliable).
///
/// Deep-space resonance integration is redone from the TLE's own epoch on
/// EVERY call (`VAL06` §VI.D: "always integrate from the epoch to the
/// required time, and restart... This was slightly less CPU efficient but
/// led to repeatable results" -- also forced by this module carrying no
/// state between calls at all, never mind between two different `tsince`).
///
/// Refuses `IOSG-F-002` ("decayed") when the computed radius drops below
/// Earth's own surface (`VAL06` §VI.A: "the decay condition simply checks
/// the position magnitude on each step").
[[nodiscard]] odl::Result<Sgp4RawState, Sgp4Error> sgp4_propagate(
    const Sgp4InitialState& state, double tsince_minutes);

/// The ergonomic entry point: a TLE and a target `time::Epoch` in, a typed
/// TEME state out. `tsince_minutes` is computed as calendar-elapsed UTC
/// minutes between the TLE's own epoch and `target`, through `leaps` --
/// deliberately NOT through `Epoch`'s own TAI-second arithmetic, because
/// SGP4's "time since epoch" is a naive elapsed-time quantity with no
/// leap-second awareness of its own (`VAL06` §II.E: "It is doubtful that a
/// leap-second capability was implemented... Any such addition is clearly
/// outside the mathematical formulation of SGP4") -- going through TAI
/// seconds would silently shift `tsince` by one second across a leap
/// second the TLE's own epoch and the target epoch straddle.
[[nodiscard]] odl::Result<frames::TemeState, Sgp4Error> propagate_teme(
    const Tle& tle, const time::Epoch& target, const time::LeapTable& leaps);

}  // namespace odl::io
