#pragma once
// odl/devkit/json.hpp — JSON, with the two behaviours the tools' output depends on that a generic library would not give.
//
//   * An object keeps its members IN FILE ORDER (Python's dict does).  NOTICE is generated by walking the manifest, and `fetch list --json` and the
//     receipts file re-serialise it; a library with sorted keys would reorder every one of them.
//   * `dumps(indent)` writes what Python's json.dumps(value, indent=2) wrote (ensure_ascii=True: every code point outside space..tilde is a \uXXXX
//     escape, in lower case, with surrogate pairs above U+FFFF).
//
// The parser refuses what a manifest must never contain (NaN, Infinity, an integer that does not fit 64 bits, a lone surrogate, nesting deeper
// than 512) and reports errors the way Python's decoder did: a message, and the line and column of the offence.

#include <cstddef>
#include <cstdint>
#include <stdexcept>
#include <string>
#include <string_view>
#include <utility>
#include <variant>
#include <vector>

namespace odl::devkit {

class Json;

struct JsonError : std::runtime_error {
    JsonError(std::string reason_, std::size_t line_, std::size_t column_, std::size_t position_);
    std::string reason;       // Python's msg: "Expecting value", "Expecting ',' delimiter", "Extra data", ...
    std::size_t line;         // 1-based
    std::size_t column;       // 1-based, in code points
    std::size_t position;     // 0-based offset in bytes
};

class Json {
public:
    using Array = std::vector<Json>;
    using Object = std::vector<std::pair<std::string, Json>>;
    enum class Kind { Null, Bool, Int, Float, String, Array, Object };

    Json() = default;
    explicit Json(bool b) : v_(b) {}
    explicit Json(std::int64_t i) : v_(i) {}
    explicit Json(double d) : v_(d) {}
    explicit Json(std::string s) : v_(std::move(s)) {}
    explicit Json(const char* s) : v_(std::string(s)) {}
    explicit Json(Array a) : v_(std::move(a)) {}
    explicit Json(Object o) : v_(std::move(o)) {}

    friend bool operator==(const Json& a, const Json& b) = default;

    [[nodiscard]] Kind kind() const noexcept { return static_cast<Kind>(v_.index()); }
    [[nodiscard]] bool is_null() const noexcept { return kind() == Kind::Null; }
    [[nodiscard]] bool is_bool() const noexcept { return kind() == Kind::Bool; }
    [[nodiscard]] bool is_int() const noexcept { return kind() == Kind::Int; }
    [[nodiscard]] bool is_number() const noexcept { return kind() == Kind::Int || kind() == Kind::Float; }
    [[nodiscard]] bool is_string() const noexcept { return kind() == Kind::String; }
    [[nodiscard]] bool is_array() const noexcept { return kind() == Kind::Array; }
    [[nodiscard]] bool is_object() const noexcept { return kind() == Kind::Object; }

    // The accessors throw std::logic_error when the value is of another kind: a tool checks the kind it needs first, and a manifest that holds a
    // number where a string belongs is refused with a message, not read as something else.
    [[nodiscard]] bool as_bool() const;
    [[nodiscard]] std::int64_t as_int() const;
    [[nodiscard]] double as_double() const;
    [[nodiscard]] const std::string& as_string() const;
    [[nodiscard]] const Array& as_array() const;
    [[nodiscard]] Array& as_array();
    [[nodiscard]] const Object& as_object() const;
    [[nodiscard]] Object& as_object();

    /// The member `key` of an object, or nullptr if this is not an object or has no such member.
    [[nodiscard]] const Json* find(std::string_view key) const noexcept;
    [[nodiscard]] Json* find(std::string_view key) noexcept;

    /// Replaces the member `key` in place if present, else appends it (an object only).
    void set(std::string key, Json value);

    /// Python's truth value: null, false, 0, 0.0, "", [] and {} are false; everything else is true.  `if not e.get(field)` is how the fetcher
    /// decided a field was missing, and an empty string counts as missing.
    [[nodiscard]] bool truthy() const noexcept;

    /// Throws JsonError.  `text` must be well-formed UTF-8 (the caller checks, with valid_utf8).
    [[nodiscard]] static Json parse(std::string_view text);

    /// json.dumps(value, indent=`indent`, ensure_ascii=`ensure_ascii`).  indent 0 is not supported (Python's would still break lines).  The
    /// committed manifest is the second kind (raw UTF-8, `§` and `—` as they are), what `fetch list --json` and the receipts write the first.
    [[nodiscard]] std::string dumps(int indent = 2, bool ensure_ascii = true) const;

private:
    // The alternatives are in the order of Kind.
    std::variant<std::monostate, bool, std::int64_t, double, std::string, Array, Object> v_;
};

}  // namespace odl::devkit
