// tests/devtools/forcemodel_comparator_header_tests.cpp — the data of the finite-difference gate's extended-precision comparator (SPEC-forcemodel.md §6.2 (e); plan L0 step 8, group C7): the hexadecimal float
// of an exact rational and what is refused, the header of degree 2 written out by hand, the header's shape for the other degrees, the refusal of a coefficient that no double holds, the tool's command line
// and what it does to a file, and the real tree.  (ctests `forcemodel_comparator_header.behaviour` and `forcemodel_comparator_header.real_tree`; the Python tool had no test of its own.)
//
// Every expectation is DERIVED BY HAND, from the solid polynomials of degree 2 (worked out in gradient_reference_tests.cpp), the norms N_nm (evaluated with GNU bc, a host tool used to derive digits and
// never by the build) and the f-strings of forcemodel_comparator_header.py, and not taken from running the port.  The hexadecimal Phi of the five coefficients of degree 2 are the Python tool's, as the
// committed header holds them; every one of them is also recomputed in forcemodel_fd_sizing_tests.cpp from hand-derived closed forms.

#include <catch2/catch_test_macros.hpp>

#include "bignum_printers.hpp"
#include "throwing_stream.hpp"

#include <odl/devkit/fs.hpp>
#include <odl/devkit/tool.hpp>

#include "forcemodel_comparator_header.hpp"
#include "forcemodel_fd_sizing.hpp"

#include <filesystem>
#include <functional>
#include <sstream>
#include <string>
#include <vector>

namespace fs = std::filesystem;
namespace ch = odl::tools::forcemodel_comparator_header;
namespace gr = odl::tools::gradient_reference;
using namespace odl::devkit;

namespace {

constexpr int kOk = 0, kFailed = 1, kArgument = 2, kInternal = 70;
constexpr const char* kCommittedHeader = "modules/forcemodel/tests/comparator_polynomials.hpp";

Rational q(std::int64_t n, std::int64_t d = 1) { return Rational(BigInt(n), BigInt(d)); }

bool contains(const std::string& haystack, const std::string& needle) { return haystack.find(needle) != std::string::npos; }
bool starts_with(const std::string& s, const std::string& prefix) { return s.compare(0, prefix.size(), prefix) == 0; }

std::vector<std::string> lines_of(const std::string& text) {
    std::vector<std::string> out;
    std::size_t from = 0;
    while (from < text.size()) {
        const std::size_t nl = text.find('\n', from);
        if (nl == std::string::npos) {
            out.push_back(text.substr(from));
            break;
        }
        out.push_back(text.substr(from, nl - from));
        from = nl + 1;
    }
    return out;
}

struct Result {
    int code = -1;
    std::string out;
    std::string err;
};

Result run_real(const std::vector<std::string>& args) {
    std::ostringstream out;
    std::ostringstream err;
    const int code = ch::run(args, Streams{out, err});
    return Result{code, out.str(), err.str()};
}

Result run_with(const std::function<gr::Poly(int, int, char)>& solid, const std::vector<std::string>& args) {
    std::ostringstream out;
    std::ostringstream err;
    const int code = ch::run_on(solid, args, Streams{out, err});
    return Result{code, out.str(), err.str()};
}

// the nineteen lines every header of this tool begins with (the committed header's, with the two names of tools turned to the C++ ones)
const char kHead[] =
    "// GENERATED by tools/forcemodel_comparator_header.cpp \xE2\x80\x94 do not edit.\n"
    "//\n"
    "// The extended-precision comparator's data (SPEC-forcemodel.md \xC2\xA7" "6.2 (e)): for each coefficient (n, m, kind) of degrees 2 \xE2\x80\x93 4 the exact\n"
    "// harmonic polynomial q, whose potential is GM a_e^n N_nm q / r^(2n+1), with N_nm and the registered bound's Phi_nm.  Each monomial\n"
    "// coefficient is a dyadic rational, exact in a double; N_nm is printed to 24 digits for a long double.\n"
    "#pragma once\n"
    "\n"
    "namespace odl::forcemodel::comparator {\n"
    "\n"
    "struct Monomial { int i, j, k; double c; };\n"
    "struct Harmonic {\n"
    "    int n, m;\n"
    "    char kind;                 ///< 'C' or 'S'\n"
    "    long double norm;          ///< N_nm, TN36-6 (6.2b)\n"
    "    double phi;                ///< Lemma 2's Phi_nm (tools/forcemodel_fd_sizing.cpp)\n"
    "    const Monomial* q;\n"
    "    int terms;\n"
    "};\n"
    "\n";

// degree 2 by hand: q = z^2 - x^2/2 - y^2/2, 3xz, 3yz, 3(x^2 - y^2), 6xy, the monomials sorted by exponents; N = sqrt 5, sqrt(5/3), sqrt(5/12) to 24 places (bc: 2.2360679774997896964091736687..., 1.2909944487358056283930884665...,
// 0.6454972243679028141965442332...); the Phi are the Python tool's (the committed header)
const char kDegreeTwo[] =
    "inline constexpr Monomial kQ_2_0_C[] = {\n"
    "    {0, 0, 2, 0x1.0000000000000p+0},\n"
    "    {0, 2, 0, -0x1.0000000000000p-1},\n"
    "    {2, 0, 0, -0x1.0000000000000p-1},\n"
    "};\n"
    "inline constexpr Monomial kQ_2_1_C[] = {\n"
    "    {1, 0, 1, 0x1.8000000000000p+1},\n"
    "};\n"
    "inline constexpr Monomial kQ_2_1_S[] = {\n"
    "    {0, 1, 1, 0x1.8000000000000p+1},\n"
    "};\n"
    "inline constexpr Monomial kQ_2_2_C[] = {\n"
    "    {0, 2, 0, -0x1.8000000000000p+1},\n"
    "    {2, 0, 0, 0x1.8000000000000p+1},\n"
    "};\n"
    "inline constexpr Monomial kQ_2_2_S[] = {\n"
    "    {1, 1, 0, 0x1.8000000000000p+2},\n"
    "};\n"
    "\n"
    "inline constexpr Harmonic kHarmonics[] = {\n"
    "    {2, 0, 'C', 2.236067977499789696409174L, 0x1.a343434eb9762p+14, kQ_2_0_C, 3},\n"
    "    {2, 1, 'C', 1.290994448735805628393088L, 0x1.6b1799add9640p+14, kQ_2_1_C, 1},\n"
    "    {2, 1, 'S', 1.290994448735805628393088L, 0x1.6b1799add9640p+14, kQ_2_1_S, 1},\n"
    "    {2, 2, 'C', 0.645497224367902814196544L, 0x1.6b1799add9640p+14, kQ_2_2_C, 2},\n"
    "    {2, 2, 'S', 0.645497224367902814196544L, 0x1.6b1799add9640p+14, kQ_2_2_S, 1},\n"
    "};\n"
    "\n"
    "}  // namespace odl::forcemodel::comparator\n";

}  // namespace

TEST_CASE("the hexadecimal float of an exact rational, and the values no double holds", "[forcemodel_comparator_header][behaviour]") {
    CHECK(ch::hexf_exact(q(0)) == "0x0.0p+0");
    CHECK(ch::hexf_exact(q(1)) == "0x1.0000000000000p+0");
    CHECK(ch::hexf_exact(q(-1)) == "-0x1.0000000000000p+0");
    CHECK(ch::hexf_exact(q(3, 8)) == "0x1.8000000000000p-2");        // 1.5 * 2^-2
    CHECK(ch::hexf_exact(q(-5, 4)) == "-0x1.4000000000000p+0");      // -1.25
    CHECK(ch::hexf_exact(q(105, 2)) == "0x1.a400000000000p+5");      // 52.5 = 1.640625 * 32
    CHECK(ch::hexf_exact(Rational(BigInt(1).shifted_left(53))) == "0x1.0000000000000p+53");
    CHECK(ch::hexf_exact(Rational((BigInt(1).shifted_left(53) - BigInt(1)))) == "0x1.fffffffffffffp+52");   // the largest odd integer a double holds
    CHECK_THROWS_AS(ch::hexf_exact(q(1, 3)), ch::InexactCoefficient);
    CHECK_THROWS_AS(ch::hexf_exact(Rational(BigInt(1).shifted_left(53) + BigInt(1))), ch::InexactCoefficient);   // 2^53 + 1 needs 54 bits
    CHECK_THROWS_AS(ch::hexf_exact(Rational(BigInt(1).shifted_left(2000))), ch::InexactCoefficient);             // beyond a double
    CHECK_THROWS_AS(ch::hexf_exact(q(1, 10)), ch::InexactCoefficient);
    try {
        (void)ch::hexf_exact(q(1, 3));
        FAIL("1/3 was taken for a double");
    } catch (const ch::InexactCoefficient& exc) {
        CHECK(std::string(exc.what()) == "not exact in a double: Fraction(1, 3)");
    }
}

TEST_CASE("the header for degree 2, written out by hand: the monomials sorted by exponents, the norms to 24 places, Phi in hexadecimal, and the counts", "[forcemodel_comparator_header][behaviour]") {
    CHECK(ch::build(2) == std::string(kHead) + kDegreeTwo);
    // the default is degree 4: 2 + 3 + 4 degrees, the five, seven and nine harmonics of degrees 2, 3 and 4 (m = 0 has no S), in 139 lines
    CHECK(ch::kNmax == 4);
    const std::string full = ch::build();
    CHECK(starts_with(full, std::string(kHead) + "inline constexpr Monomial kQ_2_0_C[] = {\n"));
    const std::vector<std::string> lines = lines_of(full);
    CHECK(lines.size() == 139);
    int blocks = 0;
    int rows = 0;
    for (const std::string& line : lines) {
        if (starts_with(line, "inline constexpr Monomial kQ_")) ++blocks;
        if (starts_with(line, "    {") && line.find("'") != std::string::npos && line.find("kQ_") != std::string::npos) ++rows;
    }
    CHECK(blocks == 21);
    CHECK(rows == 21);
    // the blocks of degree 3 and 4 are named by degree, order and kind, in that order
    CHECK(contains(full, "inline constexpr Monomial kQ_3_0_C[] = {\n"));
    CHECK_FALSE(contains(full, "kQ_3_0_S"));
    CHECK(contains(full, "inline constexpr Monomial kQ_4_4_S[] = {\n"));
    // (3,3,S) is 15 (3 x^2 y - y^3) = 45 x^2 y - 15 y^3; its monomials sorted: (0,3,0) then (2,1,0)
    CHECK(contains(full, "inline constexpr Monomial kQ_3_3_S[] = {\n    {0, 3, 0, -0x1.e000000000000p+3},\n    {2, 1, 0, 0x1.6800000000000p+5},\n};\n"));   // -15 = -1.875 * 8, 45 = 1.40625 * 32
    // a degree below 2 has no harmonic: the two blank lines of the Python's list and the table with nothing in it
    CHECK(ch::build(1) == std::string(kHead) + "\ninline constexpr Harmonic kHarmonics[] = {\n};\n\n}  // namespace odl::forcemodel::comparator\n");
    CHECK(ch::build(0) == ch::build(1));
    CHECK(ch::build(-3) == ch::build(1));
}

TEST_CASE("a coefficient that no double holds is refused, naming the coefficient and where it stands", "[forcemodel_comparator_header][behaviour]") {
    // the polynomial of (2,0,C) with a coefficient of 1/3 in the monomial z^2 (the first, in sorted order)
    const auto damaged = [](int n, int m, char kind) {
        if (n == 2 && m == 0 && kind == 'C') {
            gr::Poly bad;
            bad.set({2, 0, 0}, q(-1, 2));
            bad.set({0, 0, 2}, q(1, 3));
            return bad;
        }
        return gr::solid_polynomial(n, m, kind);
    };
    try {
        (void)ch::build(2, damaged);
        FAIL("a coefficient of 1/3 was taken for a double");
    } catch (const ch::InexactCoefficient& exc) {
        CHECK(std::string(exc.what()) == "(2, 0, 'C', 0, 0, 2, Fraction(1, 3))");
    }
    // a damage in a later coefficient: (2,2,S) with 2^53 + 1
    const auto late = [](int n, int m, char kind) {
        if (n == 2 && m == 2 && kind == 'S') {
            gr::Poly bad;
            bad.set({1, 1, 0}, Rational(BigInt(1).shifted_left(53) + BigInt(1)));
            return bad;
        }
        return gr::solid_polynomial(n, m, kind);
    };
    try {
        (void)ch::build(2, late);
        FAIL("2^53 + 1 was taken for a double");
    } catch (const ch::InexactCoefficient& exc) {
        CHECK(std::string(exc.what()) == "(2, 2, 'S', 1, 1, 0, Fraction(9007199254740993, 1))");
    }
    // the three exponents of the monomial are named in their own order, x then y then z: the two above have equal ones
    const auto distinct = [](int n, int m, char kind) {
        if (n == 2 && m == 1 && kind == 'S') {
            gr::Poly bad;
            bad.set({1, 2, 3}, q(1, 3));
            return bad;
        }
        return gr::solid_polynomial(n, m, kind);
    };
    try {
        (void)ch::build(2, distinct);
        FAIL("a coefficient of 1/3 was taken for a double");
    } catch (const ch::InexactCoefficient& exc) {
        CHECK(std::string(exc.what()) == "(2, 1, 'S', 1, 2, 3, Fraction(1, 3))");
    }
    // the tool: exit status 1, the message on standard error, nothing on standard output and no file written
    TempDir dir("odl-cmp");
    const std::string file = (dir.path() / "never.hpp").string();
    const Result refused = run_with(damaged, {"--header", file});
    CHECK(refused.code == kFailed);
    CHECK(refused.out.empty());
    CHECK(refused.err == "forcemodel_comparator_header: (2, 0, 'C', 0, 0, 2, Fraction(1, 3))\n");
    CHECK_FALSE(fs::exists(file));
    CHECK(run_with(damaged, {}).code == kFailed);
    CHECK(run_with(damaged, {"--verify", file}).code == kFailed);
}

TEST_CASE("the tool with no flag prints the header and one more newline; --header writes it, says how many lines on standard error and prints nothing", "[forcemodel_comparator_header][behaviour]") {
    const Result printed = run_real({});
    REQUIRE(printed.code == kOk);
    CHECK(printed.err.empty());
    CHECK(printed.out == ch::build() + "\n");
    TempDir dir("odl-cmp");
    const std::string file = (dir.path() / "out.hpp").string();
    const Result written = run_real({"--header", file});
    CHECK(written.code == kOk);
    CHECK(written.out.empty());
    CHECK(written.err == "wrote 139 lines to " + file + "\n");
    CHECK(read_text(file) == ch::build());
    CHECK(run_real({"--header=" + file}).code == kOk);
    // a path that cannot be written: refused, naming it
    const Result unwritable = run_real({"--header", (dir.path() / "no" / "such" / "dir.hpp").string()});
    CHECK(unwritable.code == kArgument);
    CHECK(contains(unwritable.err, "forcemodel_comparator_header: "));
    CHECK(contains(unwritable.err, "dir.hpp"));
    CHECK(unwritable.out.empty());
}

TEST_CASE("--verify says whether a committed header is exactly what the generator emits, and wins over --header", "[forcemodel_comparator_header][behaviour]") {
    TempDir dir("odl-cmp");
    const std::string file = (dir.path() / "committed.hpp").string();
    REQUIRE(run_real({"--header", file}).code == kOk);
    const Result same = run_real({"--verify", file});
    CHECK(same.code == kOk);
    CHECK(same.err == "ok       the committed header is exactly what the generator emits\n");
    CHECK(same.out.empty());
    std::string text = read_text(file);
    text[text.find("kHarmonics") + 1] = 'X';
    write_text(file, text);
    const Result different = run_real({"--verify", file});
    CHECK(different.code == kFailed);
    CHECK(different.err == "MISMATCH the committed header differs from the generator's output\n");
    // Windows line ends are read as Python's read_text reads them
    REQUIRE(run_real({"--header", file}).code == kOk);
    std::string with_crlf;
    for (const char c : read_text(file)) {
        if (c == '\n') with_crlf += '\r';
        with_crlf += c;
    }
    write_text(file, with_crlf);
    CHECK(run_real({"--verify", file}).code == kOk);
    const std::string other = (dir.path() / "other.hpp").string();
    CHECK(run_real({"--header", other, "--verify", file}).code == kOk);
    CHECK_FALSE(fs::exists(other));
    const Result missing = run_real({"--verify", (dir.path() / "nowhere.hpp").string()});
    CHECK(missing.code == kArgument);
    CHECK(contains(missing.err, "nowhere.hpp"));
    CHECK(run_real({"--verify", dir.path().string()}).code == kArgument);
    write_text(file, "\xE9 not utf-8");
    const Result latin = run_real({"--verify", file});
    CHECK(latin.code == kArgument);
    CHECK(contains(latin.err, "committed.hpp"));
}

TEST_CASE("the command line: -h prints the usage and the options; an option that is not one, or without its argument, is an error of exit status 2", "[forcemodel_comparator_header][behaviour]") {
    const std::string usage = "usage: forcemodel_comparator_header [-h] [--header HEADER] [--verify VERIFY]\n";
    static const char kHelp[] = R"HELP(usage: forcemodel_comparator_header [-h] [--header HEADER] [--verify VERIFY]

The data the finite-difference gate's extended-precision comparator needs (SPEC-forcemodel.md §6.2 (e)): the harmonic polynomials of degrees 2 - 4, exactly, and the constants of the registered
truncation bound (the header modules/forcemodel/tests/comparator_polynomials.hpp).

options:
  -h, --help       show this help and exit
  --header HEADER  write a C++ header here instead of printing
  --verify VERIFY  compare this committed header with what the generator emits; exit 1 if they differ

exit codes: 0 emitted / the committed header is what the generator emits   1 they differ, or a coefficient is not exact in a double
            2 an argument error, or a file that cannot be read or written
)HELP";   // the text of the tool's own help, pinned
    for (const char* flag : {"-h", "--help"}) {
        const Result help = run_real({flag});
        CHECK(help.code == kOk);
        CHECK(starts_with(help.out, usage));
        CHECK(help.out == kHelp);
        CHECK(contains(help.out, "  --header HEADER  write a C++ header here instead of printing\n"));
        CHECK(contains(help.out, "  --verify VERIFY  compare this committed header with what the generator emits; exit 1 if they differ\n"));
        CHECK(contains(help.out, "exit codes: 0 emitted / the committed header is what the generator emits   1 they differ, or a coefficient is not exact in a double\n"));
        CHECK(help.err.empty());
    }
    const Result unknown = run_real({"--check"});
    CHECK(unknown.code == kArgument);
    CHECK(unknown.err == usage + "forcemodel_comparator_header: error: unrecognized arguments: --check\n");
    CHECK(unknown.out.empty());
    CHECK(run_real({"stray"}).code == kArgument);
    const Result bare = run_real({"--verify"});
    CHECK(bare.code == kArgument);
    CHECK(bare.err == usage + "forcemodel_comparator_header: error: argument --verify: expected one argument\n");
    CHECK(run_real({"--header", "--verify"}).code == kArgument);
    // a word that begins with two dashes is an option, however many more follow: `---x` is not the argument of --verify
    const Result dashes = run_real({"--verify", "---x"});
    CHECK(dashes.code == kArgument);
    CHECK(dashes.err == usage + "forcemodel_comparator_header: error: argument --verify: expected one argument\n");
    CHECK(run_real({"-h", "--check"}).code == kOk);
    CHECK(run_real({"--check", "-h"}).code == kArgument);
}

TEST_CASE("an error the tool did not anticipate is reported with exit status 70", "[forcemodel_comparator_header][behaviour]") {
    odl::devtools_testing::ThrowingStream out;
    std::ostringstream err;
    CHECK(ch::run({}, Streams{out, err}) == kInternal);
    CHECK(err.str() == "forcemodel_comparator_header: internal error: boom\n");
}

TEST_CASE("the committed header IS what the tool writes, byte for byte, and its Phi are the sizing's", "[forcemodel_comparator_header][real_tree]") {
    const fs::path header = fs::path(ODL_TREE_ROOT) / kCommittedHeader;
    const Result verified = run_real({"--verify", header.string()});
    CHECK(verified.err == "ok       the committed header is exactly what the generator emits\n");
    CHECK(verified.code == kOk);
    const std::vector<std::string> lines = lines_of(read_text(header));
    CHECK(lines.size() == 139);
    CHECK(lines[0] == "// GENERATED by tools/forcemodel_comparator_header.cpp \xE2\x80\x94 do not edit.");
    CHECK(lines[14] == "    double phi;                ///< Lemma 2's Phi_nm (tools/forcemodel_fd_sizing.cpp)");
}
