// tests/devtools/legendre_reference_tests.cpp — the reference values of GRAV-A-003, from the definition (plan L0 step 8, group C7): N_nm squared and the integer coefficients of the definition's sum against the
// direct formula, the evaluation against values known in closed form (low degrees by hand, and for every one of the high-degree pairs the value at u = 1, P_n^(m)(1) = (n+m)! / (2^m m! (n-m)!), evaluated
// with GNU bc, a host tool used to derive digits and never by the build), against the Python's own order of evaluation at moderate degrees, the two-precision guard and its refusal, the text of the header,
// the tool's command line and what it does to a file, and the real tree.  (ctests `legendre_reference.behaviour` and `legendre_reference.real_tree`; the Python tool had no test of its own, and its
// header no ctest.)
//
// Every expectation is DERIVED BY HAND, from the definition, from closed forms worked out in the comments and from the print statements and f-strings of legendre_reference.py, and not taken from running
// the port.

#include <catch2/catch_test_macros.hpp>

#include "bignum_printers.hpp"
#include "throwing_stream.hpp"

#include <odl/devkit/decimal.hpp>
#include <odl/devkit/fs.hpp>
#include <odl/devkit/tool.hpp>

#include "legendre_reference.hpp"

#include <algorithm>
#include <filesystem>
#include <sstream>
#include <string>
#include <utility>
#include <vector>

namespace fs = std::filesystem;
namespace lg = odl::tools::legendre_reference;
using namespace odl::devkit;

namespace {

constexpr int kOk = 0, kFailed = 1, kArgument = 2, kInternal = 70;
constexpr const char* kCommittedHeader = "modules/gravity/tests/legendre_reference.hpp";

Rational q(std::int64_t n, std::int64_t d = 1) { return Rational(BigInt(n), BigInt(d)); }
Decimal D(const char* text) { return Decimal::from_string(text); }

bool contains(const std::string& haystack, const std::string& needle) { return haystack.find(needle) != std::string::npos; }
bool starts_with(const std::string& s, const std::string& prefix) { return s.compare(0, prefix.size(), prefix) == 0; }

std::vector<std::string> lines_of(const std::string& text) {
    std::vector<std::string> out;
    std::size_t from = 0;
    while (from < text.size()) {
        const std::size_t nl = text.find('\n', from);
        if (nl == std::string::npos) {
            out.push_back(text.substr(from));
            break;
        }
        out.push_back(text.substr(from, nl - from));
        from = nl + 1;
    }
    return out;
}

struct Result {
    int code = -1;
    std::string out;
    std::string err;
};

Result run_on(const lg::Settings& settings, const std::vector<std::string>& args) {
    std::ostringstream out;
    std::ostringstream err;
    const int code = lg::run_on(settings, args, Streams{out, err});
    return Result{code, out.str(), err.str()};
}

/// |got - want| <= 10^-digits |want| (in 300 digits)
bool near(const Decimal& got, const Decimal& want, int digits) {
    LocalContext ctx(300);
    const Decimal tol = D(("1e-" + std::to_string(digits)).c_str());
    return (got - want).abs() <= tol * want.abs();
}

/// the rounding of a number to 60 digits, as the tool's values are
Decimal round60(const char* text) {
    LocalContext ctx(60);
    return +D(text);
}

BigInt factorial(int n) {
    BigInt out(1);
    for (int i = 2; i <= n; ++i) out *= BigInt(i);
    return out;
}

BigInt comb(int n, int k) { return factorial(n) / (factorial(k) * factorial(n - k)); }

/// two points, two values of u: four rows
lg::Settings small_settings() {
    lg::Settings s;
    s.points = {{2, 0}, {2, 1}};
    s.sines = {"0", "1"};
    return s;
}

// the 32 lines the header begins with (the committed header's, the name of the tool turned to the C++ one)
const char kHead[] = R"HEAD(// GENERATED by tools/legendre_reference.cpp — do not edit.
//
// Reference values for GRAV-A-003, computed from the DEFINITION of the
// associated Legendre function in high-precision decimal arithmetic, never
// from SPEC-gravity §4.4's recursion.  A test whose reference came from the
// same recursion it is testing would pass for a recursion that is wrong.
//
// Each value was evaluated at two precisions and is emitted only if the two
// agree to 50 significant digits; at degree 2190 about 660 digits are lost to
// cancellation before the answer appears, and a naive 50-digit evaluation
// returns confident nonsense rather than failing.
#pragma once

namespace odl::gravity::reference {

// Most of these values do not fit in a double: max over m of
// Pbar'_{2190,m}(1) is 10^457.864, which is 10^150 past the largest double.
// So each row carries BOTH the direct value, where there is one, and the
// base-10 logarithm of its magnitude with its sign, which there always is.
// A row with representable = false is checked through the scaled path, not
// skipped: the values that do not fit are exactly the ones worth checking.
struct LegendreValue {
    int n;
    int m;
    double sin_phi;
    bool representable;
    double pbar_factored;   ///< Pbar_nm(sin phi) / cos^m(phi), or 0 if it does not fit
    double log10_abs;       ///< log10 |Pbar'_nm|, or 0 when the value is 0
    double sign;            ///< +1, -1 or 0
};

inline constexpr LegendreValue kLegendre[] = {
)HEAD";

}  // namespace

// ======================================================================================================================================== the integer coefficients

TEST_CASE("N_nm squared, exactly: (2 - delta_0m)(2n+1)(n-m)!/(n+m)!", "[legendre_reference][behaviour]") {
    CHECK(lg::norm_squared(0, 0) == q(1));
    CHECK(lg::norm_squared(2, 0) == q(5));
    CHECK(lg::norm_squared(2, 1) == q(5, 3));         // 2 * 5 * 1!/3!
    CHECK(lg::norm_squared(2, 2) == q(5, 12));        // 2 * 5 * 0!/4!
    CHECK(lg::norm_squared(3, 3) == q(7, 360));       // 2 * 7 / 6!
    CHECK(lg::norm_squared(4, 3) == q(1, 280));       // 2 * 9 * 1!/7!
    CHECK(lg::norm_squared(10, 0) == q(21));
}

TEST_CASE("the coefficients of 2^n P_n^(m)(u), by hand and by the direct formula", "[legendre_reference][behaviour]") {
    const auto ints = [](std::initializer_list<std::int64_t> values) {
        std::vector<BigInt> out;
        for (const std::int64_t v : values) out.push_back(BigInt(v));
        return out;
    };
    // 2^n P_n(u): n = 0: 1; n = 1: 2u; n = 2: 6u^2 - 2 (P_2 = (3u^2 - 1)/2, times 4); n = 4: 70u^4 - 60u^2 + 6 (P_4 = (35u^4 - 30u^2 + 3)/8, times 16); n = 5: 252u^5 - 280u^3 + 60u (P_5 = (63u^5 - 70u^3 + 15u)/8, times 32)
    CHECK(lg::coefficients(0, 0) == ints({1}));
    CHECK(lg::coefficients(1, 0) == ints({2}));
    CHECK(lg::coefficients(2, 0) == ints({6, -2}));
    CHECK(lg::coefficients(4, 0) == ints({70, -60, 6}));
    CHECK(lg::coefficients(5, 0) == ints({252, -280, 60}));
    // derivatives: P_1' = 1 (times 2); P_2' = 3u (times 4), P_2'' = 3 (times 4); P_3' = (15u^2 - 3)/2 (times 8: 60u^2 - 12); P_4' = (140u^3 - 60u)/8 (times 16: 280u^3 - 120u); P_4''' = 105u (times 16: 1680u)
    CHECK(lg::coefficients(1, 1) == ints({2}));
    CHECK(lg::coefficients(2, 1) == ints({12}));
    CHECK(lg::coefficients(2, 2) == ints({12}));
    CHECK(lg::coefficients(3, 1) == ints({60, -12}));
    CHECK(lg::coefficients(4, 1) == ints({280, -120}));
    CHECK(lg::coefficients(4, 3) == ints({1680}));
    // no term: m > n, and the arguments that are no degree or order
    CHECK(lg::coefficients(2, 3).empty());
    CHECK(lg::coefficients(-1, 0).empty());
    CHECK(lg::coefficients(2, -1).empty());
    // against the definition's formula, written out once more: (-1)^j C(n,j) C(2n-2j,n) (n-2j)!/(n-2j-m)!, for every degree up to 12 and every order
    for (int n = 0; n <= 12; ++n) {
        for (int m = 0; m <= n; ++m) {
            std::vector<BigInt> want;
            for (int j = 0; n - 2 * j - m >= 0; ++j) {
                BigInt c = comb(n, j) * comb(2 * n - 2 * j, n) * factorial(n - 2 * j) / factorial(n - 2 * j - m);
                if (j % 2 == 1) c = -c;
                want.push_back(c);
            }
            INFO("(" << n << "," << m << ")");
            CHECK(lg::coefficients(n, m) == want);
        }
    }
    // and at a degree where the integers have thousands of digits the ratio of consecutive terms is still exact (it throws if it is not): n = 2190, m = 1095 has 548 terms
    const std::vector<BigInt> big = lg::coefficients(2190, 1095);
    CHECK(big.size() == 548);
    CHECK(big.front() == comb(4380, 2190) * factorial(2190) / factorial(1095));
    CHECK(big.back().sign() < 0);   // 547 sign changes: odd
}

// ======================================================================================================================================== the values

TEST_CASE("Pbar'_nm(u) against closed forms at low degree: (2,0) at 0, 1/2 and 1, (2,1), (2,2), (3,3), (4,3)", "[legendre_reference][behaviour]") {
    // Pbar'_{2,0}(u) = sqrt 5 (3u^2 - 1)/2:  -sqrt5/2 at 0, -sqrt5/8 at 1/2, sqrt 5 at 1;   Pbar'_{2,1}(u) = sqrt(5/3) 3u = sqrt 15 u;   Pbar'_{n,n} = N_nn (2n-1)!!, no u at all:  (2,2) = 3 sqrt(5/12) = sqrt(15/4),
    // (3,3) = 15 sqrt(7/360);   Pbar'_{4,3}(u) = 105 u / sqrt 280.  (bc, 70 digits)
    CHECK(near(lg::pbar_factored(2, 0, "0", 80), D("-1.1180339887498948482045868343656381177203091798057628621354486227052604"), 70));
    CHECK(near(lg::pbar_factored(2, 0, "0.5", 80), D("-0.2795084971874737120511467085914095294300772949514407155338621556763151"), 70));
    CHECK(near(lg::pbar_factored(2, 0, "1", 80), D("2.2360679774997896964091736687312762354406183596115257242708972454105209"), 70));
    CHECK(near(lg::pbar_factored(2, 1, "1", 80), D("3.8729833462074168851792653997823996108329217052915908265875737661134830"), 70));
    CHECK(near(lg::pbar_factored(2, 1, "0.5", 80), D("1.9364916731037084425896326998911998054164608526457954132937868830567415"), 70));   // sqrt 15 / 2
    CHECK(lg::pbar_factored(2, 1, "0", 80).is_zero());
    CHECK(near(lg::pbar_factored(2, 2, "0", 80), D("1.9364916731037084425896326998911998054164608526457954132937868830567415"), 70));
    CHECK(near(lg::pbar_factored(2, 2, "0.3971478906347806", 80), D("1.9364916731037084425896326998911998054164608526457954132937868830567415"), 70));
    CHECK(near(lg::pbar_factored(3, 3, "0.7", 80), D("2.0916500663351888699454300644629687234820384232466804995279788577010440"), 60));   // bc divides 7/360 first, at 70 places
    CHECK(near(lg::pbar_factored(4, 3, "0.5", 80), D("3.1374750995027833049181450966944530852230576348700207492919682865515704"), 70));
    CHECK(near(lg::pbar_factored(4, 3, "1", 80), D("6.2749501990055666098362901933889061704461152697400414985839365731031407"), 70));
    CHECK(lg::pbar_factored(4, 3, "0", 80).is_zero());
    CHECK(lg::pbar_factored(10, 7, "0", 80).is_zero());   // n - m odd: an odd polynomial, zero at 0
    // the value has the precision of the evaluation: 80 digits are 80 digits, and the result is rounded to them
    CHECK(lg::pbar_factored(2, 0, "1", 80).digits() == 80);
    CHECK(lg::pbar_factored(2, 0, "1", 40).digits() == 40);
    // an order above the degree has no N_nm: the Python's factorial(n - m) raised ValueError, and so does the port (std::invalid_argument)
    CHECK_THROWS_AS(lg::pbar_factored(2, 3, "0.5", 50), std::invalid_argument);
    try {
        (void)lg::pbar_factored(2, 3, "0.5", 50);
        FAIL("an order above the degree was accepted");
    } catch (const std::invalid_argument& exc) {
        CHECK(std::string(exc.what()) == "factorial() not defined for negative values");
    }
}

TEST_CASE("Pbar'_nm(1) = sqrt( 2 (2n+1) (n+m)! / (4^m (m!)^2 (n-m)!) ) at every high-degree pair of the tool, to the 55th digit, at the precision the tool uses", "[legendre_reference][behaviour]") {
    // P_n^(m)(1) = (n+m)! / (2^m m! (n-m)!) and N_nm^2 = 2 (2n+1) (n-m)!/(n+m)!, so Pbar'(1)^2 = 2 (2n+1) (n+m)! / (4^m (m!)^2 (n-m)!), and sqrt(2n+1) for m = 0.  The values below are bc's, at 110 digits of scale.
    struct Row {
        int n;
        int m;
        const char* expected;
    };
    const std::vector<Row> rows = {
        {2, 1, "3.8729833462074168851792653997823996108329217052915908265875737661134830E0"},
        {2, 2, "1.9364916731037084425896326998911998054164608526457954132937868830567415E0"},
        {4, 3, "6.2749501990055666098362901933889061704461152697400414985839365731031407E0"},
        {10, 7, "7.7346874936871237499994404073971231689900365095900768286748164658549856E1"},
        {60, 30, "4.0877619394289066662008286613080091825565128081433994172993342316796181E12"},
        {360, 360, "6.5470270986345057411432384640790434366610775718100102880854873085330204E0"},
        {1000, 500, "3.1455067202043868626237926522823838077563015184568117042823424924701528E207"},
        {1500, 1499, "5.1213003219438152686500849519044380403823711207316800725460889927873344E2"},
        {2190, 0, "6.6189122973491649068211005990192086191030869363189613564415340462511587E1"},
        {2190, 1, "1.0252148187087426215379204050948257573458446228697655794398802523384055E5"},
        {2190, 1095, "1.6426933570349334237477083523945340770965646603979006410341003634687614E454"},
        {2190, 2190, "1.0277576859743819341060612823004125747644269905455723754957132882012040E1"},
    };
    for (const Row& row : rows) {
        INFO("(" << row.n << "," << row.m << ")");
        const Decimal got = lg::pbar_factored(row.n, row.m, "1", 4 * row.n + 500);
        CHECK(near(got, D(row.expected), 55));
    }
    // the sqrt(2n+1) of the zonal term, with no factorial at all: sqrt 4381 = 66.189122973491649068...
    CHECK(near(lg::pbar_factored(2190, 0, "1", 9260), D("66.189122973491649068211005990192086191030869363189613564415340462511587"), 55));
}

TEST_CASE("the evaluation by Horner's rule in u^2 agrees with the Python's, term by term with u^e, at moderate degrees and over the whole range of u", "[legendre_reference][behaviour]") {
    const std::vector<std::pair<int, int>> pairs = {{3, 1}, {6, 2}, {10, 7}, {16, 0}, {20, 13}, {24, 24}, {31, 5}, {40, 20}};
    const std::vector<const char*> sines = {"0", "0.1", "0.3971478906347806", "0.7071067811865476", "0.9396926207859084", "0.9999984769132877", "1"};
    for (const auto& [n, m] : pairs) {
        for (const char* u : sines) {
            INFO("(" << n << "," << m << ") u = " << u);
            // sum_j coeff_j u^(n-2j-m), a power of u for every term, at 220 digits; N_nm and 2^n likewise
            Decimal slow;
            {
                LocalContext ctx(220);
                const Decimal x = D(u);
                const Rational nsq = lg::norm_squared(n, m);
                const Decimal norm = (Decimal(nsq.numerator()) / Decimal(nsq.denominator())).sqrt();
                Decimal total(0);
                const std::vector<BigInt> coeffs = lg::coefficients(n, m);
                for (std::size_t j = 0; j < coeffs.size(); ++j) {
                    const int e = n - 2 * static_cast<int>(j) - m;
                    total = total + Decimal(coeffs[j]) * (e != 0 ? x.pow(Decimal(e)) : Decimal(1));
                }
                slow = +(norm * total / Decimal(2).pow(Decimal(n)));
            }
            const Decimal fast = lg::pbar_factored(n, m, u, 240);
            if (slow.is_zero()) {
                CHECK(fast.is_zero());
            } else {
                CHECK(near(fast, slow, 150));
            }
        }
    }
}

TEST_CASE("value: the 60-digit rounding of two evaluations that agree, zero for a zero, and the guard that refuses what loses its digits", "[legendre_reference][behaviour]") {
    const std::int64_t prec_before = getcontext().prec;
    // closed forms, rounded to 60 digits as the tool's values are
    CHECK(lg::value(2, 0, "0") == round60("-1.1180339887498948482045868343656381177203091798057628621354486227052604"));
    CHECK(lg::value(2, 0, "1") == round60("2.2360679774997896964091736687312762354406183596115257242708972454105209"));
    CHECK(lg::value(2, 0, "0.5") == round60("-0.2795084971874737120511467085914095294300772949514407155338621556763151"));
    CHECK(lg::value(2, 1, "1") == round60("3.8729833462074168851792653997823996108329217052915908265875737661134830"));
    CHECK(lg::value(2, 0, "1").digits() == 60);
    CHECK(lg::value(2, 0, "1").to_string() == "2.23606797749978969640917366873127623544061835961152572427090");   // the trailing zero of the 60th digit is kept
    // a zero is the number zero, whatever the two evaluations made of it
    CHECK(lg::value(2, 1, "0").to_string() == "0");
    CHECK(lg::value(4, 3, "0").to_string() == "0");
    CHECK(lg::value(10, 7, "0").to_string() == "0");
    CHECK(lg::value(2190, 1, "0").to_string() == "0");
    // the global context is not touched (the Python set its precision to 60 for the rest of the run; nothing after that depended on it)
    CHECK(getcontext().prec == prec_before);

    // Sixty digits of working precision at degree 60, order 0: P_60(u) is of order 1 and the terms of its sum reach C(120,60) = 10^34.98, so some eighteen digits are lost to cancellation before the answer
    // appears; the two evaluations (at 60 and at 90 digits) agree to about 1e-42 and not to 1e-50: refused.  The same sum at degree 2, where nothing cancels, is accepted at the same precisions.
    lg::Precisions sixty;
    sixty.per_degree = 0;
    sixty.base = 60;
    sixty.gap = 30;
    CHECK(near(lg::value(2, 0, "0.9396926207859084", sixty), lg::value(2, 0, "0.9396926207859084"), 55));
    try {
        (void)lg::value(60, 0, "0.9396926207859084", sixty);
        FAIL("a value that loses eighteen of its sixty digits was accepted");
    } catch (const lg::RefusedError& exc) {
        const std::string what = exc.what();
        CHECK(starts_with(what, "Pbar'_60,0(u=0.9396926207859084) does not agree between 60 and 90 digits: "));
        const std::string numbers = what.substr(what.find("digits: ") + 8);
        const std::size_t vs = numbers.find(" vs ");
        REQUIRE(vs != std::string::npos);
        const Decimal a = D(numbers.substr(0, vs).c_str());
        const Decimal b = D(numbers.substr(vs + 4).c_str());
        LocalContext ctx(100);
        CHECK(((a - b) / b).abs() > D("1e-50"));
        CHECK(((a - b) / b).abs() < D("1e-30"));   // a loss of eighteen digits: about 1e-42, and nothing like the noise of a sum with no digit left
    }
    // with the tool's own precisions the point is accepted, and its value is the one at higher precision rounded to 60 digits
    CHECK(near(lg::value(60, 0, "0.9396926207859084"), lg::value(60, 0, "0.9396926207859084", lg::Precisions{4, 400, 300}), 55));
    // a precision too low for ANY agreement (20 digits against 25: the two roundings to 60 digits differ at 1e-20) refuses even degree 2
    lg::Precisions twenty;
    twenty.per_degree = 0;
    twenty.base = 20;
    twenty.gap = 5;
    CHECK_THROWS_AS(lg::value(2, 0, "0.9396926207859084", twenty), lg::RefusedError);
    // one evaluation that is exactly zero and one that is not DISAGREE, in either order, and are not "a zero": 2^2 P_2(u) = 6 u^2 - 2, and at ONE digit of precision u = 0.5773502691896258 (sqrt(1/3) to 16
    // digits) gives u^2 = 0.3333... -> 0.3, 6 * 0.3 = 1.8 -> 2, 2 - 2 = 0 exactly, while at forty digits the sum is of the order 1e-16
    lg::Precisions one_digit;
    one_digit.per_degree = 0;
    one_digit.base = 1;
    one_digit.gap = 39;
    CHECK_THROWS_AS(lg::value(2, 0, "0.5773502691896258", one_digit), lg::RefusedError);
    lg::Precisions backwards;   // the high precision first and the one digit second: the other operand is the exact zero
    backwards.per_degree = 0;
    backwards.base = 40;
    backwards.gap = -39;
    CHECK_THROWS_AS(lg::value(2, 0, "0.5773502691896258", backwards), lg::RefusedError);
    // while the value at a hundred digits, where the cancellation of sixteen of them still leaves more than fifty, is not zero, and two exact zeros (the point u = 0 at either precision) are the number zero
    CHECK_FALSE(lg::value(2, 0, "0.5773502691896258", lg::Precisions{0, 100, 20}).is_zero());
    CHECK(lg::value(2, 0, "0.5773502691896258", lg::Precisions{0, 100, 20}).abs() < D("1e-15"));
    CHECK(lg::value(3, 0, "0", one_digit).is_zero());
    // the tool's precisions are 4n + 400 and 300 more
    CHECK(lg::Precisions{}.per_degree == 4);
    CHECK(lg::Precisions{}.base == 400);
    CHECK(lg::Precisions{}.gap == 300);
}

// ======================================================================================================================================== the header

TEST_CASE("the text of the header for two points and two values of u: the 32 fixed lines, a line each, and the end", "[legendre_reference][behaviour]") {
    const Result r = run_on(small_settings(), {});
    REQUIRE(r.code == kOk);
    // standard error: one line a value, in the order of the points and of u; the value is str() of the 60-digit Decimal, a zero is "0"
    CHECK(r.err ==
          "ok       Pbar'_2,0(u=0) = -1.11803398874989484820458683436563811772030917980576286213545\n"
          "ok       Pbar'_2,0(u=1) = 2.23606797749978969640917366873127623544061835961152572427090\n"
          "ok       Pbar'_2,1(u=0) = 0\n"
          "ok       Pbar'_2,1(u=1) = 3.87298334620741688517926539978239961083292170529159082658757\n");
    // standard output: the header and print()'s newline.  Rows: -sqrt5/2 = -1.118...485e+0 (18 digits), log10 = 0.04845500650402820717939 -> 0.04845500650402821;  sqrt5 = 2.23606797749978970e+0, log10 0.34948500216800940;
    // zero: no logarithm; sqrt15 = 3.87298334620741689e+0, log10 0.58804562952784062
    const std::string expected = std::string(kHead) +
                                 "    {2, 0, 0, true, -1.11803398874989485e+0, 0.04845500650402821, -1.0},\n"
                                 "    {2, 0, 1, true, 2.23606797749978970e+0, 0.34948500216800940, 1.0},\n"
                                 "    {2, 1, 0, true, 0.0, 0.0, 0.0},\n"
                                 "    {2, 1, 1, true, 3.87298334620741689e+0, 0.58804562952784062, 1.0},\n"
                                 "};\n"
                                 "\n"
                                 "}  // namespace odl::gravity::reference\n";
    CHECK(r.out == expected + "\n");
    CHECK(lines_of(kHead).size() == 32);
    CHECK(lines_of(r.out).size() == 32 + 4 + 3 + 1);
    // the value of a number that does not fit a double is not given, and the logarithm is: (2190,1095) at 1 is 1.64269...e454
    lg::Settings big;
    big.points = {{2190, 1095}};
    big.sines = {"1"};
    const Result b = run_on(big, {});
    REQUIRE(b.code == kOk);
    CHECK(contains(b.out, "    {2190, 1095, 1, false, 0.0, 454.21555650088079483, 1.0},\n"));   // log10 1.6426933570349334237e454 = 454 + log10 1.6426933570349334237 = 454.2155565008807948...
    // a number of order 10^40 does fit: (2190, 1095) at 0.3971478906347806 is -5.78e40 (the committed header's row; the sign is -1)
    lg::Settings mid;
    mid.points = {{2190, 1095}};
    mid.sines = {"0.3971478906347806"};
    const Result m = run_on(mid, {});
    CHECK(contains(m.out, "    {2190, 1095, 0.3971478906347806, true, -5.78366328698899815e+40, 40.76220300128867676, -1.0},\n"));
}

// ======================================================================================================================================== the tool

TEST_CASE("--header writes the header, says how many values on standard error (after a blank line) and prints nothing; the same run twice is the same", "[legendre_reference][behaviour]") {
    const lg::Settings settings = small_settings();
    const Result printed = run_on(settings, {});
    TempDir dir("odl-leg");
    const std::string file = (dir.path() / "out.hpp").string();
    const Result written = run_on(settings, {"--header", file});
    CHECK(written.code == kOk);
    CHECK(written.out.empty());
    CHECK(written.err == printed.err + "\nwrote 4 values to " + file + "\n");
    CHECK(read_text(file) + "\n" == printed.out);
    CHECK(run_on(settings, {}).out == printed.out);
    CHECK(run_on(settings, {"--header=" + file}).code == kOk);
    const Result unwritable = run_on(settings, {"--header", (dir.path() / "no" / "such" / "dir.hpp").string()});
    CHECK(unwritable.code == kArgument);
    CHECK(contains(unwritable.err, "legendre_reference: "));
    CHECK(contains(unwritable.err, "dir.hpp"));
    CHECK(unwritable.out.empty());
}

TEST_CASE("--verify says whether a committed header is exactly what the generator emits, and wins over --header", "[legendre_reference][behaviour]") {
    const lg::Settings settings = small_settings();
    TempDir dir("odl-leg");
    const std::string file = (dir.path() / "committed.hpp").string();
    REQUIRE(run_on(settings, {"--header", file}).code == kOk);
    const Result same = run_on(settings, {"--verify", file});
    CHECK(same.code == kOk);
    CHECK(contains(same.err, "ok       the committed header is exactly what the generator emits\n"));
    CHECK(same.err.substr(same.err.rfind("ok       the committed")) == "ok       the committed header is exactly what the generator emits\n");
    CHECK(same.out.empty());
    std::string text = read_text(file);
    text[text.find("kLegendre") + 1] = 'X';
    write_text(file, text);
    const Result different = run_on(settings, {"--verify", file});
    CHECK(different.code == kFailed);
    CHECK(different.err.substr(different.err.rfind("MISMATCH")) == "MISMATCH the committed header differs from the generator's output\n");
    REQUIRE(run_on(settings, {"--header", file}).code == kOk);
    std::string with_crlf;
    for (const char c : read_text(file)) {
        if (c == '\n') with_crlf += '\r';
        with_crlf += c;
    }
    write_text(file, with_crlf);
    CHECK(run_on(settings, {"--verify", file}).code == kOk);
    const std::string other = (dir.path() / "other.hpp").string();
    CHECK(run_on(settings, {"--header", other, "--verify", file}).code == kOk);
    CHECK_FALSE(fs::exists(other));
    const Result missing = run_on(settings, {"--verify", (dir.path() / "nowhere.hpp").string()});
    CHECK(missing.code == kArgument);
    CHECK(contains(missing.err, "nowhere.hpp"));
    CHECK(run_on(settings, {"--verify", dir.path().string()}).code == kArgument);
    write_text(file, "\xE9 not utf-8");
    const Result latin = run_on(settings, {"--verify", file});
    CHECK(latin.code == kArgument);
    CHECK(contains(latin.err, "committed.hpp"));
}

TEST_CASE("a value that does not agree between the two precisions is REFUSED: standard error says which, the exit status is 1, and nothing is written", "[legendre_reference][behaviour]") {
    lg::Settings settings;
    settings.points = {{2, 0}, {60, 0}};
    settings.sines = {"0.9396926207859084"};
    settings.precisions = lg::Precisions{0, 60, 30};   // sixty digits and ninety: the first point loses nothing to cancellation, the second loses eighteen of them
    TempDir dir("odl-leg");
    const std::string file = (dir.path() / "never.hpp").string();
    const Result refused = run_on(settings, {"--header", file});
    CHECK(refused.code == kFailed);
    CHECK(refused.out.empty());
    CHECK(starts_with(refused.err, "ok       Pbar'_2,0(u=0.9396926207859084) = "));
    CHECK(contains(refused.err, "\nREFUSED  Pbar'_60,0(u=0.9396926207859084) does not agree between 60 and 90 digits: "));
    CHECK(refused.err.back() == '\n');
    CHECK_FALSE(fs::exists(file));
}

TEST_CASE("the command line: -h prints the usage and the options; an option that is not one, or without its argument, is an error of exit status 2", "[legendre_reference][behaviour]") {
    const lg::Settings settings = small_settings();
    const std::string usage = "usage: legendre_reference [-h] [--header HEADER] [--verify VERIFY]\n";
    static const char kHelp[] = R"HELP(usage: legendre_reference [-h] [--header HEADER] [--verify VERIFY]

Reference values for GRAV-A-003, from the DEFINITION of the associated Legendre function: Pbar'_nm(u) at 13 (n, m) pairs and six values of sin(phi), each evaluated at two precisions and emitted only if
the two agree to 50 significant digits (the header modules/gravity/tests/legendre_reference.hpp).

options:
  -h, --help       show this help and exit
  --header HEADER  write a C++ header here instead of printing
  --verify VERIFY  compare this committed header with what the generator emits; exit 1 if they differ

exit codes: 0 emitted / the committed header is what the generator emits   1 a value failed its two-precision agreement check, or the committed header differs
            2 an argument error, or a file that cannot be read or written
)HELP";   // the text of the tool's own help, pinned
    for (const char* flag : {"-h", "--help"}) {
        const Result help = run_on(settings, {flag});
        CHECK(help.code == kOk);
        CHECK(starts_with(help.out, usage));
        CHECK(help.out == kHelp);
        CHECK(contains(help.out, "  --header HEADER  write a C++ header here instead of printing\n"));
        CHECK(contains(help.out, "  --verify VERIFY  compare this committed header with what the generator emits; exit 1 if they differ\n"));
        CHECK(contains(help.out, "exit codes: 0 emitted / the committed header is what the generator emits   1 a value failed its two-precision agreement check, or the committed header differs\n"));
        CHECK(help.err.empty());
    }
    const Result unknown = run_on(settings, {"--check"});
    CHECK(unknown.code == kArgument);
    CHECK(unknown.err == usage + "legendre_reference: error: unrecognized arguments: --check\n");
    CHECK(unknown.out.empty());
    CHECK(run_on(settings, {"stray"}).code == kArgument);
    const Result bare = run_on(settings, {"--header"});
    CHECK(bare.code == kArgument);
    CHECK(bare.err == usage + "legendre_reference: error: argument --header: expected one argument\n");
    CHECK(run_on(settings, {"--verify", "--header"}).code == kArgument);
    // a word that begins with two dashes is an option, however many more follow: `---x` is not the argument of --verify
    const Result dashes = run_on(settings, {"--verify", "---x"});
    CHECK(dashes.code == kArgument);
    CHECK(dashes.err == usage + "legendre_reference: error: argument --verify: expected one argument\n");
    CHECK(run_on(settings, {"-h", "--check"}).code == kOk);
    CHECK(run_on(settings, {"--check", "-h"}).code == kArgument);
    // `run` is `run_on` the real settings: the help and a refusal of the arguments never reach the computation
    std::ostringstream real_out;
    std::ostringstream real_err;
    CHECK(lg::run({"-h"}, Streams{real_out, real_err}) == kOk);
    CHECK(starts_with(real_out.str(), usage));
    CHECK(lg::run({"--frobnicate"}, Streams{real_out, real_err}) == kArgument);
    CHECK(contains(real_err.str(), "unrecognized arguments: --frobnicate"));
}

TEST_CASE("an error the tool did not anticipate is reported with exit status 70", "[legendre_reference][behaviour]") {
    odl::devtools_testing::ThrowingStream out;
    std::ostringstream err;
    CHECK(lg::run_on(small_settings(), {}, Streams{out, err}) == kInternal);
    CHECK(contains(err.str(), "legendre_reference: internal error: boom\n"));
}

TEST_CASE("the default settings are the 13 pairs and the six values of sin(phi) of GRAV-A-003: 78 values", "[legendre_reference][behaviour]") {
    const lg::Settings s = lg::default_settings();
    CHECK(s.points.size() == 13);
    CHECK(s.sines.size() == 6);
    // the thirteen pairs, one by one: degree 2 at every order, the first tesseral and sectoral terms, the mid-degree ones, and the four extremes of degree 2190 (the committed header's rows)
    CHECK(s.points == (std::vector<std::pair<int, int>>{{2, 0}, {2, 1}, {2, 2}, {4, 3}, {10, 7}, {60, 30}, {360, 360}, {1000, 500}, {1500, 1499}, {2190, 0}, {2190, 1}, {2190, 1095}, {2190, 2190}}));
    CHECK(s.sines == (std::vector<std::string>{"0", "0.3971478906347806", "0.7071067811865476", "0.9396926207859084", "0.9999984769132877", "1"}));
    CHECK(s.precisions.per_degree == 4);
    CHECK(s.precisions.base == 400);
    CHECK(s.precisions.gap == 300);
}

// ======================================================================================================================================== the real tree

TEST_CASE("a sample of the tool's rows, at the degrees where the digits are made of the most cancellation, are rows of the committed header, byte for byte", "[legendre_reference][real_tree]") {
    const fs::path header = fs::path(ODL_TREE_ROOT) / kCommittedHeader;
    const std::vector<std::string> committed = lines_of(read_text(header));
    REQUIRE(committed.size() == 113);
    CHECK(committed[0] == "// GENERATED by tools/legendre_reference.cpp \xE2\x80\x94 do not edit.");
    lg::Settings sample = lg::default_settings();
    sample.points = {{2, 0}, {2, 1}, {2, 2}, {4, 3}, {10, 7}, {60, 30}, {360, 360}, {1000, 500}, {1500, 1499}, {2190, 1095}};   // the low degrees, whose values are of the order of one, and the high ones, where the digits are made of cancellation
    TempDir dir("odl-leg");
    const std::string file = (dir.path() / "sample.hpp").string();
    const Result r = run_on(sample, {"--header", file});
    REQUIRE(r.code == kOk);
    const std::vector<std::string> rows = lines_of(read_text(file));
    REQUIRE(rows.size() == 32 + 60 + 3);
    for (std::size_t k = 32; k < 32 + 60; ++k) {
        INFO(rows[k]);
        CHECK(std::find(committed.begin(), committed.end(), rows[k]) != committed.end());
    }
    // and the fixed lines are the committed file's
    for (std::size_t k = 0; k < 32; ++k) CHECK(rows[k] == committed[k]);
}
