// GENERATED by tools/estimation_sizing.cpp -- do not edit.
//
// The FROZEN FIGURES of SPEC-estimation 6 (L7 step 2), registered before any code of the estimator existed: the rows' bit checksums, the exact condition numbers, the
// scale exponents, the derived bounds, the predictions of the refusals.  Every double is a hexadecimal float, so the header carries the generator's values exactly.
#pragma once

#include <cmath>

namespace odl::estimation::registered {

inline constexpr int kMaxN = 11;
inline constexpr double kUnitRoundoff = 0x1p-53;
inline constexpr double kEtaRep = 0x1.0147ae147ae14p-52;              // 2.01 u: a decimal datum rounded to double through long double, doubled for a product
inline constexpr double kCertifiedRelative = 0x1.6849b86a12b9bp-47;   // one unit of the 15th printed digit, worst case

struct NistFigures {
    const char* name;
    int n, m;
    unsigned long long checksum;      ///< sum of the bit patterns of every design entry and response, in row order, mod 2^64
    int e[kMaxN];                     ///< the scale exponents (EST-R-201)
    double kappa, lam_min_a, lam_max_a, q1, dx_norm, r_norm;
    double theta_n_code, theta_n_test, b_code, b_test, b_q, b_rho, b_sigma, sigma0_exact;
    double b_pair, gap, tau_s, cos_min;   ///< EST-A-209 (two units), EST-A-212 (the weakest direction's angle bound)
    double kappa_i[kMaxN];
    double qdiag[kMaxN];              ///< (N^-1)_ii in the units of the parameters
    double weakest_exact[kMaxN];      ///< the exact eigenvector of the smallest eigenvalue of N_s, largest component positive
    double rho_exact[kMaxN * (kMaxN - 1) / 2];   ///< the exact correlations, row-major upper triangle
    int breakdown_index;              ///< -1: the Cholesky factorisation of the scaled matrix completes
    double breakdown_pivot;
};

inline constexpr NistFigures kNist[] = {
    {"Norris", 2, 36, 1643446187301902744ULL, {3, 12, 0, 0, 0, 0, 0, 0, 0, 0, 0},
     0x1.f8013979519b6p+2, 0x1.cf3338f5a6642p-3, 0x1.c61998e14b338p+0, 0x1.eb0767613d530p+2, 0x1.97215b9cf486ap+11, 0x1.96fa81b95f26fp+11,
     0x1.5800000000028p-47, 0x1.68147ae147b0ap-47, 0x1.069247a6de879p-41, 0x1.195ca1a738bb2p-41, 0x1.8e040c6205ebdp-45, 0x1.2a8309498470ep-43, 0x1.5e2274e693730p-41, 0x1.c50408821e134p-1,
     0x1.1a501454e9648p-40, 0x1.040f9f43e38cbp-3, 0x1.401f037425077p-43, 0x1.0000000000000p+0,
     {0x1.3f0cfd9c01a9ep+1, 0x1.3f0cfd9c01a9ep+1, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0},
     {0x1.1b99c4fc7341ap-4, 0x1.fab8cae80528fp-23, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0},
     {0x1.76f7bf7313508p-1, -0x1.5ca163b73e29ap-1, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0},
     {-0x1.8c3331c296670p-1, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0},
     -1, 0.0},
    {"Pontius", 3, 40, 10166487458293071352ULL, {3, 23, 45, 0, 0, 0, 0, 0, 0, 0, 0},
     0x1.60dada6738d15p+8, 0x1.077963ae8c93ep-7, 0x1.5e38646cc4ac9p+1, 0x1.2ac2fb23f7b35p+7, 0x1.0a3c5961fa464p+3, 0x1.07b159eeb3b62p+3,
     0x1.2c00000000026p-46, 0x1.380f5c28f5c4fp-46, 0x1.fe46b5d326988p-37, 0x1.0a601ac30ccf3p-36, 0x1.2f35220d3b01cp-39, 0x1.c6cfb313d882ap-38, 0x1.06c9168e23c53p-49, 0x1.ae49ca70ecafdp-13,
     0x1.0fbaecdd35ad2p-35, 0x1.9c4117a3216a2p-5, 0x1.1f0e4f3884e66p-38, 0x1.0000000000000p+0,
     {0x1.623ee08fb823fp+3, 0x1.31a2e8ba2e8bap+6, 0x1.494eccf69bf7dp+5, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0},
     {0x1.1b658072f9b66p-2, 0x1.4d0ef4385033bp-41, 0x1.1692af1c8af27p-84, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0},
     {0x1.50b0362f6ad6dp-2, -0x1.291412f63fcdep-1, 0x1.7d82266d23005p-1, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0},
     {-0x1.c7116f70c670ap-1, 0x1.8fee78d7372d1p-1, -0x1.f1548d32ec77cp-1, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0},
     -1, 0.0},
    {"NoInt1", 1, 11, 9771087157161623552ULL, {8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
     0x1.0000000000000p+0, 0x1.0000000000000p+0, 0x1.0000000000000p+0, 0x1.68245b6b9aa4ep+0, 0x1.bfb99d614686cp+8, 0x1.bfddfeb59dc81p+8,
     0x1.e000000000010p-50, 0x1.1028f5c28f5cbp-49, 0x1.24a7997944d7ep-46, 0x1.03063b8abbfd7p-45, 0x1.1028f5c28f5d4p-49, 0x1.983d70a3d70bep-48, 0x1.208ffb08ea954p-43, 0x1.c8a4d58d07ad2p+1,
     0x1.68879b9403812p-45, 0x0.0p+0, 0x1.51a215b4e0fb5p-48, 0x0.0p+0,
     {0x1.0000000000000p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0},
     {0x1.68245b6b9aa4ep-16, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0},
     {0x1.0000000000000p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0},
     {0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0},
     -1, 0.0},
    {"NoInt2", 1, 3, 9251519534525841408ULL, {3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
     0x1.0000000000000p+0, 0x1.0000000000000p+0, 0x1.0000000000000p+0, 0x1.a98ef606a63bep-1, 0x1.986f48e4fbfd5p+2, 0x1.99ccc999fff00p+2,
     0x1.c000000000004p-51, 0x1.2051eb851eb86p-50, 0x1.0a3da13e22370p-48, 0x1.117aaf24c7680p-46, 0x1.2051eb851eb8bp-50, 0x1.b07ae147ae150p-49, 0x1.2732b206246a5p-48, 0x1.7a23166210bb4p-2,
     0x1.aae420ff63276p-47, 0x0.0p+0, 0x1.745d1745d1749p-50, 0x0.0p+0,
     {0x1.0000000000000p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0},
     {0x1.a98ef606a63bep-7, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0},
     {0x1.0000000000000p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0},
     {0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0},
     -1, 0.0},
    {"Filip", 11, 82, 10632479737673943491ULL, {3, 6, 9, 12, 14, 17, 20, 24, 27, 30, 33},
     0x1.793b3f6579339p+64, 0x1.aa520cf54cfd4p-62, 0x1.39478891b4407p+3, 0x1.de9494228ede0p+61, 0x1.9d03f15a070a2p+24, 0x1.ed60a3ceb030dp+2,
     0x1.3f0000000004cp-43, 0x1.44870a3d70a8ap-43, 0x1.2a2d937b34af1p+21, 0x1.2f5840b460ab0p+21, HUGE_VAL, HUGE_VAL, 0x1.8134284023cc6p+9, 0x1.b6d4975275950p-9,
     0x1.31ed9750f6a8ep+22, 0x1.163a3d3f44612p-10, 0x1.6d591d9da7eadp+19, 0x0.0p+0,
     {0x1.2eaf104ef626ap+39, 0x1.4e10e6fb2674fp+46, 0x1.5ebe65f4a2a47p+51, 0x1.1cdea45a00a8cp+55, 0x1.a5e76f1866b38p+57, 0x1.2f7438274c7c9p+59, 0x1.abd6ad06fd153p+59, 0x1.1d0d4c2798ccep+59, 0x1.4658c40ea8315p+57, 0x1.047327934af59p+54, 0x1.4d24a347ff902p+48},
     {0x1.d87b6aa0b86e4p+32, 0x1.a090363522003p+34, 0x1.2145e8b3704e1p+34, 0x1.127f88e33279bp+32, 0x1.b4c0046f7221ep+28, 0x1.3e3bae3f9085dp+24, 0x1.b3eff4d9bf144p+18, 0x1.11de32cc20067p+12, 0x1.214c42ea7ed6fp+4, 0x1.a3546ae66df05p-6, 0x1.e1526221fc2fep-18},
     {0x1.c49589c16a4b1p-12, 0x1.aada861118f11p-8, 0x1.6506b47130b1dp-5, 0x1.5ccfabed7b4bdp-3, 0x1.b8efcfc3826f1p-3, 0x1.78e962112d62ap-2, 0x1.b96e50228ce76p-2, 0x1.5ddc60388c095p-1, 0x1.67514ddea26a3p-2, 0x1.b001f3a28f621p-4, 0x1.cdf0f72618057p-7},
     {0x1.ffcd4ed936d00p-1, 0x1.ff35503e5b76dp-1, 0x1.fe39a916887d3p-1, 0x1.fcdde525eeeeep-1, 0x1.fb2736da49702p-1, 0x1.f91c23d1edcffp-1, 0x1.f6c4289eecc1cp-1, 0x1.f4275cb090ccfp-1, 0x1.f14e1d0174083p-1, 0x1.ee40c1f5a6860p-1, 0x1.ffcd3b5884dccp-1, 0x1.ff35cd3571266p-1, 0x1.fe3c78f38d889p-1, 0x1.fce5bfca676e3p-1, 0x1.fb3791c13ab41p-1, 0x1.f938f35e640c6p-1, 0x1.f6f1a1680f69bp-1, 0x1.f469b9e004f2dp-1, 0x1.f1a96f2bf3336p-1, 0x1.ffcd8e59ec24ap-1, 0x1.ff37da8bda3f9p-1, 0x1.fe42ab4441d45p-1, 0x1.fcf34fe548b27p-1, 0x1.fb5048e433c47p-1, 0x1.f960ec0d4bf8ap-1, 0x1.f72d0c57f04bep-1, 0x1.f4bcaabfb0c4cp-1, 0x1.ffce4337e3a7ep-1, 0x1.ff3b5d7325cdap-1, 0x1.fe4bf49574bc5p-1, 0x1.fd05fabd93c12p-1, 0x1.fb7053b92906cp-1, 0x1.f9927c43c7ab2p-1, 0x1.f77439042abe9p-1, 0x1.ffcf511f8b5c0p-1, 0x1.ff402c8d0bb68p-1, 0x1.fe57edd42cd38p-1, 0x1.fd1cfd5f46fb5p-1, 0x1.fb9677b5bf27ap-1, 0x1.f9cbdb183dd9bp-1, 0x1.ffd0ac2773165p-1, 0x1.ff46147fddf1dp-1, 0x1.fe661e81f0f9bp-1, 0x1.fd377e02a3e71p-1, 0x1.fbc161eb7da40p-1, 0x1.ffd246819f65fp-1, 0x1.ff4cdc92dfe6cp-1, 0x1.fe760678d31c4p-1, 0x1.fd549c25c95b7p-1, 0x1.ffd4119898d54p-1, 0x1.ff544ad0d08bdp-1, 0x1.fe87266eaaa5bp-1, 0x1.ffd5ff039a9b1p-1, 0x1.ff5c27784d5fcp-1, 0x1.ffd8014978009p-1},
     9, -0x1.34c04a9c06580p-39},
    {"Longley", 7, 16, 6014946862758992282ULL, {2, 9, 21, 14, 13, 19, 13, 0, 0, 0, 0},
     0x1.a60acbb3608bfp+30, 0x1.f78e221dd362bp-29, 0x1.b7210f220ef6fp+2, 0x1.1bb6fdd2e5a87p+28, 0x1.309c979fb5c11p+24, 0x1.fefae8f29f295p+17,
     0x1.0a0000000000ap-45, 0x1.1811eb851eb8fp-45, 0x1.2769898f14f59p-15, 0x1.37152d86a5178p-15, 0x1.1cc4efea32bd8p-17, 0x1.ab2767df4c1c4p-16, 0x1.0052372d48248p-25, 0x1.30daa490a1046p+8,
     0x1.3eeaff8050b9ep-14, 0x1.6a143ed4a7feap-11, 0x1.1bb907f44e8f8p-16, 0x1.fffffffec51e1p-1,
     {0x1.0459652289e51p+27, 0x1.9551e0b592737p+13, 0x1.e17844a40289fp+14, 0x1.c462134c3b42ep+8, 0x1.ca63cc6ab54bcp+5, 0x1.db7b79b8b575dp+16, 0x1.043dacfe38b7bp+27, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0},
     {0x1.0459652289e51p+23, 0x1.3dcaf2ec8e618p-4, 0x1.9eb0534357386p-27, 0x1.587d70c6652a3p-19, 0x1.093b52e99f198p-21, 0x1.273efa4f56e78p-21, 0x1.1dbbdf0878e7bp+1, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0},
     {-0x1.617c453246827p-1, 0x1.afb866f4f7530p-10, -0x1.68d9b5cd99204p-7, -0x1.51810c1f73e2fp-10, -0x1.8831f5e4583ffp-13, 0x1.2c8fd78843932p-7, 0x1.7251f898160b4p-1, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0},
     {-0x1.a3b428ebb035dp-3, 0x1.a1da210d1760bp-1, 0x1.ac0675f3eaf4ap-1, 0x1.1975274d2a9fdp-1, -0x1.a48b0c9e5d2c1p-2, -0x1.ffd74e31cdfc8p-1, -0x1.4c80981befdb1p-1, -0x1.1c28f2b3081c8p-1, -0x1.652fb2752d385p-2, 0x1.517fd52f88999p-1, 0x1.7d82bf1f4ab2dp-3, 0x1.e426a61f2b290p-1, 0x1.dfd9fa463d433p-2, -0x1.aa99f1d9db352p-1, -0x1.9a75ea598d161p-1, 0x1.3cb4a16db3bf9p-1, -0x1.843a2c258512cp-1, -0x1.a5f09ae19bc67p-1, -0x1.82e59a09d65b5p-3, -0x1.1946a94ddd577p-1, 0x1.8d79ca0abb8adp-2, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0},
     -1, 0.0},
    {"Wampler1", 6, 21, 14090403090914082816ULL, {2, 6, 10, 14, 18, 22, 0, 0, 0, 0, 0},
     0x1.40c828b727c2dp+22, 0x1.2095d22956444p-20, 0x1.5328616894a71p+2, 0x1.48e5677457a33p+20, 0x1.2c77563850fa6p+22, 0x1.3d171b2f7e644p+22,
     0x1.e00000000001ap-46, 0x1.f81eb851eb86ap-46, 0x1.7a154a75139b2p-23, 0x1.9040b012052b8p-23, 0x1.bf32ac0e5cf3ap-26, 0x1.4f66010ac5b6cp-24, 0x1.63b5b41f68119p-15, 0x0.0p+0,
     0x1.9b5660c40f5f2p-22, 0x1.670c31bff2b09p-7, 0x1.da4838fd51ccbp-25, 0x1.ffffffffffff2p-1,
     {0x1.176eea48b2b5bp+4, 0x1.67c9523379f43p+11, 0x1.33ce872f134e5p+16, 0x1.86c38b6a23b47p+18, 0x1.8a2dacfdac160p+18, 0x1.ab968748ac4e6p+15, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0},
     {0x1.a9cd95c41c829p-1, 0x1.00bd54867ea11p+0, 0x1.be9f50db49856p-4, 0x1.e49a0e5ee075dp-10, 0x1.8000578fa893ap-18, 0x1.374dbaf7253d3p-29, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0},
     {-0x1.bfc655a4c5de2p-10, 0x1.c7133a85c36dap-5, -0x1.4c5c1d73fe0f5p-2, 0x1.62123bc89099ap-1, -0x1.3a1197b8f4583p-1, 0x1.8a3771e867769p-3, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0},
     {-0x1.80d085f728710p-1, 0x1.2b609152ad66fp-1, -0x1.f5a3049ffd1ebp-2, 0x1.b6de956563442p-2, -0x1.8a8a819c131f4p-2, -0x1.ea56cfb103c77p-1, 0x1.ca89bed3e03dbp-1, -0x1.ad8777cb5645cp-1, 0x1.94933b05a574cp-1, -0x1.f7be43785f187p-1, 0x1.e81e87d4ffbedp-1, -0x1.d70c14bec6208p-1, -0x1.fbaa377374757p-1, 0x1.f26acc541d4aap-1, -0x1.fd54eb0dd930cp-1, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0},
     -1, 0.0},
    {"Wampler2", 6, 21, 12942210813523722554ULL, {2, 6, 10, 14, 18, 22, 0, 0, 0, 0, 0},
     0x1.40c828b727c2dp+22, 0x1.2095d22956444p-20, 0x1.5328616894a71p+2, 0x1.48e5677457a33p+20, 0x1.d6963a3754201p+5, 0x1.a726025084252p+6,
     0x1.e00000000001ap-46, 0x1.f81eb851eb86ap-46, 0x1.ab307e0045b6bp-23, 0x1.c60f21f6f925dp-23, 0x1.bf32ac0e5cf3ap-26, 0x1.4f66010ac5b6cp-24, 0x1.3c02c4666d3ddp-31, 0x0.0p+0,
     0x1.d37e71d5e448cp-22, 0x1.670c31bff2b09p-7, 0x1.da4838fd51ccbp-25, 0x1.ffffffffffff2p-1,
     {0x1.176eea48b2b5bp+4, 0x1.67c9523379f43p+11, 0x1.33ce872f134e5p+16, 0x1.86c38b6a23b47p+18, 0x1.8a2dacfdac160p+18, 0x1.ab968748ac4e6p+15, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0},
     {0x1.a9cd95c41c829p-1, 0x1.00bd54867ea11p+0, 0x1.be9f50db49856p-4, 0x1.e49a0e5ee075dp-10, 0x1.8000578fa893ap-18, 0x1.374dbaf7253d3p-29, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0},
     {-0x1.bfc655a4c5de2p-10, 0x1.c7133a85c36dap-5, -0x1.4c5c1d73fe0f5p-2, 0x1.62123bc89099ap-1, -0x1.3a1197b8f4583p-1, 0x1.8a3771e867769p-3, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0},
     {-0x1.80d085f728710p-1, 0x1.2b609152ad66fp-1, -0x1.f5a3049ffd1ebp-2, 0x1.b6de956563442p-2, -0x1.8a8a819c131f4p-2, -0x1.ea56cfb103c77p-1, 0x1.ca89bed3e03dbp-1, -0x1.ad8777cb5645cp-1, 0x1.94933b05a574cp-1, -0x1.f7be43785f187p-1, 0x1.e81e87d4ffbedp-1, -0x1.d70c14bec6208p-1, -0x1.fbaa377374757p-1, 0x1.f26acc541d4aap-1, -0x1.fd54eb0dd930cp-1, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0},
     -1, 0.0},
    {"Wampler3", 6, 21, 14206977361697570816ULL, {2, 6, 10, 14, 18, 22, 0, 0, 0, 0, 0},
     0x1.40c828b727c2dp+22, 0x1.2095d22956444p-20, 0x1.5328616894a71p+2, 0x1.48e5677457a33p+20, 0x1.2c77563850fa6p+22, 0x1.3d173b59f59b9p+22,
     0x1.e00000000001ap-46, 0x1.f81eb851eb86ap-46, 0x1.7a1551883913cp-23, 0x1.9040b7d284e6cp-23, 0x1.bf32ac0e5cf3ap-26, 0x1.4f66010ac5b6cp-24, 0x1.70dfd63ab8102p-29, 0x1.2704a408efd60p+11,
     0x1.9b5668db3c3bcp-22, 0x1.670c31bff2b09p-7, 0x1.da4838fd51ccbp-25, 0x1.ffffffffffff2p-1,
     {0x1.176eea48b2b5bp+4, 0x1.67c9523379f43p+11, 0x1.33ce872f134e5p+16, 0x1.86c38b6a23b47p+18, 0x1.8a2dacfdac160p+18, 0x1.ab968748ac4e6p+15, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0},
     {0x1.a9cd95c41c829p-1, 0x1.00bd54867ea11p+0, 0x1.be9f50db49856p-4, 0x1.e49a0e5ee075dp-10, 0x1.8000578fa893ap-18, 0x1.374dbaf7253d3p-29, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0},
     {-0x1.bfc655a4c5de2p-10, 0x1.c7133a85c36dap-5, -0x1.4c5c1d73fe0f5p-2, 0x1.62123bc89099ap-1, -0x1.3a1197b8f4583p-1, 0x1.8a3771e867769p-3, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0},
     {-0x1.80d085f728710p-1, 0x1.2b609152ad66fp-1, -0x1.f5a3049ffd1ebp-2, 0x1.b6de956563442p-2, -0x1.8a8a819c131f4p-2, -0x1.ea56cfb103c77p-1, 0x1.ca89bed3e03dbp-1, -0x1.ad8777cb5645cp-1, 0x1.94933b05a574cp-1, -0x1.f7be43785f187p-1, 0x1.e81e87d4ffbedp-1, -0x1.d70c14bec6208p-1, -0x1.fbaa377374757p-1, 0x1.f26acc541d4aap-1, -0x1.fd54eb0dd930cp-1, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0},
     -1, 0.0},
    {"Wampler4", 6, 21, 14428732811022172160ULL, {2, 6, 10, 14, 18, 22, 0, 0, 0, 0, 0},
     0x1.40c828b727c2dp+22, 0x1.2095d22956444p-20, 0x1.5328616894a71p+2, 0x1.48e5677457a33p+20, 0x1.2c77563850fa6p+22, 0x1.41f602a153161p+22,
     0x1.e00000000001ap-46, 0x1.f81eb851eb86ap-46, 0x1.7b278b30c7ed1p-23, 0x1.916d30c848ebap-23, 0x1.bf32ac0e5cf3ap-26, 0x1.4f66010ac5b6cp-24, 0x1.9adeb815b9dbcp-29, 0x1.ccf7404df6be6p+17,
     0x1.9c9001779ad65p-22, 0x1.670c31bff2b09p-7, 0x1.da4838fd51ccbp-25, 0x1.ffffffffffff2p-1,
     {0x1.176eea48b2b5bp+4, 0x1.67c9523379f43p+11, 0x1.33ce872f134e5p+16, 0x1.86c38b6a23b47p+18, 0x1.8a2dacfdac160p+18, 0x1.ab968748ac4e6p+15, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0},
     {0x1.a9cd95c41c829p-1, 0x1.00bd54867ea11p+0, 0x1.be9f50db49856p-4, 0x1.e49a0e5ee075dp-10, 0x1.8000578fa893ap-18, 0x1.374dbaf7253d3p-29, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0},
     {-0x1.bfc655a4c5de2p-10, 0x1.c7133a85c36dap-5, -0x1.4c5c1d73fe0f5p-2, 0x1.62123bc89099ap-1, -0x1.3a1197b8f4583p-1, 0x1.8a3771e867769p-3, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0},
     {-0x1.80d085f728710p-1, 0x1.2b609152ad66fp-1, -0x1.f5a3049ffd1ebp-2, 0x1.b6de956563442p-2, -0x1.8a8a819c131f4p-2, -0x1.ea56cfb103c77p-1, 0x1.ca89bed3e03dbp-1, -0x1.ad8777cb5645cp-1, 0x1.94933b05a574cp-1, -0x1.f7be43785f187p-1, 0x1.e81e87d4ffbedp-1, -0x1.d70c14bec6208p-1, -0x1.fbaa377374757p-1, 0x1.f26acc541d4aap-1, -0x1.fd54eb0dd930cp-1, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0},
     -1, 0.0},
    {"Wampler5", 6, 21, 14970292273336549376ULL, {2, 6, 10, 14, 18, 22, 0, 0, 0, 0, 0},
     0x1.40c828b727c2dp+22, 0x1.2095d22956444p-20, 0x1.5328616894a71p+2, 0x1.48e5677457a33p+20, 0x1.2c77563850fa6p+22, 0x1.5d41b5181abeap+26,
     0x1.e00000000001ap-46, 0x1.f81eb851eb86ap-46, 0x1.805b5e86fd1d1p-21, 0x1.a1a40810a9db0p-21, 0x1.bf32ac0e5cf3ap-26, 0x1.4f66010ac5b6cp-24, 0x1.ce008da1d32cap-25, 0x1.68212a3ce8c4cp+24,
     0x1.b2485c4e6494fp-20, 0x1.670c31bff2b09p-7, 0x1.da4838fd51ccbp-25, 0x1.ffffffffffff2p-1,
     {0x1.176eea48b2b5bp+4, 0x1.67c9523379f43p+11, 0x1.33ce872f134e5p+16, 0x1.86c38b6a23b47p+18, 0x1.8a2dacfdac160p+18, 0x1.ab968748ac4e6p+15, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0},
     {0x1.a9cd95c41c829p-1, 0x1.00bd54867ea11p+0, 0x1.be9f50db49856p-4, 0x1.e49a0e5ee075dp-10, 0x1.8000578fa893ap-18, 0x1.374dbaf7253d3p-29, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0},
     {-0x1.bfc655a4c5de2p-10, 0x1.c7133a85c36dap-5, -0x1.4c5c1d73fe0f5p-2, 0x1.62123bc89099ap-1, -0x1.3a1197b8f4583p-1, 0x1.8a3771e867769p-3, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0},
     {-0x1.80d085f728710p-1, 0x1.2b609152ad66fp-1, -0x1.f5a3049ffd1ebp-2, 0x1.b6de956563442p-2, -0x1.8a8a819c131f4p-2, -0x1.ea56cfb103c77p-1, 0x1.ca89bed3e03dbp-1, -0x1.ad8777cb5645cp-1, 0x1.94933b05a574cp-1, -0x1.f7be43785f187p-1, 0x1.e81e87d4ffbedp-1, -0x1.d70c14bec6208p-1, -0x1.fbaa377374757p-1, 0x1.f26acc541d4aap-1, -0x1.fd54eb0dd930cp-1, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0},
     -1, 0.0},
};

/// Filip with B6 .. B10 ELIMINATED at their certified values (EST-A-210).
struct HatchFigures { int n_free, dof; int e[kMaxN]; int breakdown_index; double kappa, lam_min_a, q1, dx_norm, r_orig, r_mod, magnitude, d_e_v, b_code, b_test, digits_exact_vs_certified; };
inline constexpr HatchFigures kHatchFilip = {6, 76, {3, 6, 9, 12, 14, 17, 0, 0, 0, 0, 0}, -1,
    0x1.6288234a8a7fcp+32, 0x1.c466d5c99e5d5p-30, 0x1.3a36586e7dd40p+30, 0x1.edffad021e161p+23, 0x1.ed60a3ceb030dp+2, 0x1.ed9561ae64825p+22, 0x1.2102849fcdd80p+25, 0x1.4b04a75c89c0ep+24,
    0x1.d4a8bfc086ed7p-12, 0x1.bd322308b142fp-11, 0x1.7437a1d463589p+3};

/// The unscaled decision rule U of EST-A-209: min pivot / max pivot of the Cholesky factor of the UNSCALED normal matrix.
inline constexpr double kRuleUPontius = 0x1.5c375ae3adb47p-79;
inline constexpr double kRuleUPontiusEquilibrated = 0x1.8e05d285ad13dp-6;

/// Demmel's worked example (LAPACK Working Note 14, page 4): H = D A D, D = diag(1, 1e5, 1e-10, 1e15), b = (42, -26, 24, 34).
struct DemmelFigures { int e[4]; double p[4]; double kappa_a, lam_min_a, lam_max_a, kappa_h, kappa_ns, q1, theta_n, b, b_exact_a, published_bound; };
inline constexpr DemmelFigures kDemmel = {{0, 17, -33, 50}, {-0x1.74ece35231f5bp-2, 0x1.7ce3ca4378ce3p-4, 0x1.668b17e8fd5c2p-1, -0x1.36bbdd218bf28p-1},
    0x1.9b1fe65478eb9p+3, 0x1.19afe49ed8263p-3, 0x1.c4607dc8ae6cep+0, 0x1.aa1aa1968e183p+167, 0x1.8dbe17964672bp+3, 0x1.627e227150fd5p+3, 0x1.c010624dd2f21p-48, 0x1.3639b62441056p-42, 0x1.973479e036980p-45, 0x1.0e374a4f8e0b4p-46};

/// SYN-dependent: three parameters, the third a DUPLICATE of the first (EST-A-211).
inline constexpr int kSynDependentBreakdownIndex = 2;
inline constexpr double kSynDependentBreakdownPivot = 0x0.0p+0;
/// SYN-nearly-dependent: two parameters whose columns differ by 2^-23 in two entries (EST-A-211).
inline constexpr double kSynNearKappa = 0x1.0000000000010p+49;
inline constexpr double kSynNearLamMin = 0x1.ffffffffffff0p-49;
inline constexpr double kSynNearQ1 = 0x1.0000000000010p+48;
inline constexpr double kSynNearB = 0x1.600000800001ep+1;

/// The tridiagonal(2, -1) problems of EST-A-203: n, Theta_s(n), lambda_min(A), the per-column bound Theta_s / lambda_min(A).
struct TridiagonalFigures { int n; double theta_s, lam_min_a, b_col; };
inline constexpr TridiagonalFigures kTridiagonal[] = {
    {1, 0x1.0000000000001p-51, 0x1.fffffffffffffp-1, 0x1.0000000000002p-51},
    {2, 0x1.c000000000004p-50, 0x1.ffffffffffffep-2, 0x1.c000000000006p-49},
    {5, 0x1.4000000000005p-47, 0x1.126145e9ecd54p-3, 0x1.2a906689b97fcp-44},
    {10, 0x1.3600000000009p-45, 0x1.4bd56432afa90p-5, 0x1.de4fe466e786dp-41},
    {20, 0x1.3100000000011p-43, 0x1.6dfdd20b0f9c0p-7, 0x1.aaad351f8c213p-37},
    {40, 0x1.2e80000000021p-41, 0x1.80975fe95e300p-9, 0x1.92b694f38481ap-33},
};

}  // namespace odl::estimation::registered
