#!/usr/bin/env python3
"""Convert an ILRS Consolidated Prediction Format file into the ECI text format
the fits read, so a laser ranging target's predicted orbit can seed or be
compared against one computed here.

CPF is what the laser stations actually point with: an Earth-fixed position
every minute, generated by whoever holds the tracking data for the target. It
carries no velocity, so velocity here is differentiated from the positions
AFTER they are rotated into ECI - differentiating the Earth-fixed positions and
then rotating would leave out the frame's own rotation and be wrong by about
0.5 km/s, which still looks like an orbit.

The rotation is done by this tree's own ECEF2ECI, one call per epoch, so the
result is in exactly the frame the propagator integrates in.

Usage:
    cpf2eci.py <file.nxt> <out.eci> [--step N] [--from YYYY-MM-DDTHH:MM]
                                    [--hours H] [--sat-id N]

    --step   use every Nth CPF record (default 5, i.e. 5 minutes)
    --time-bias S   the object runs S seconds AHEAD of the prediction

A prediction for a high area-to-mass object is wrong almost entirely along
track, because what is mismodelled is drag and radiation pressure and both act
along the velocity. Laser stations deal with this by applying a time bias -
pointing at where the prediction says the object will be a few seconds later -
and the ILRS distributes measured biases for exactly that reason. --time-bias
does the same here: it takes the predicted state at t + S and stamps it t.

For LightSail-2 over 31 Aug to 3 Sep 2019 the bias measured against the laser
data itself grows from 4.3 s to 15.0 s, about 3.5 s a day or 26 km a day, and
removing it drops the prediction error from 74 km to 341 m. That residue is the
prediction's real cross-track and radial accuracy.

A CPF file is a PREDICTION, made before the pass it covers. For a high
area-to-mass object it degrades quickly, so treat it as a starting guess and
not as truth.
"""

import subprocess
import sys
import os
import datetime

BINDIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "bin")
# The utilities resolve res/ relative to their working directory, so they have
# to be run from bin/ or they cannot find the ephemeris.
BIN = os.path.join(BINDIR, "ECEF2ECI")


def mjd_to_datetime(mjd, sod):
    return (datetime.datetime(1858, 11, 17) + datetime.timedelta(days=mjd) +
            datetime.timedelta(seconds=sod))


def main(argv):
    if len(argv) < 3:
        raise SystemExit(__doc__)
    src, dst = argv[1], argv[2]
    step = 5
    sat_id = 1
    t_from = None
    hours = None
    time_bias = 0.0
    for i, a in enumerate(argv):
        if a == "--step":
            step = int(argv[i + 1])
        elif a == "--sat-id":
            sat_id = int(argv[i + 1])
        elif a == "--from":
            t_from = datetime.datetime.strptime(argv[i + 1], "%Y-%m-%dT%H:%M")
        elif a == "--hours":
            hours = float(argv[i + 1])
        elif a == "--time-bias":
            time_bias = float(argv[i + 1])

    recs = []
    for line in open(src, encoding="latin-1"):
        f = line.split()
        if not f or f[0] != "10":
            continue
        mjd, sod = int(f[2]), float(f[3])
        x, y, z = (float(v) / 1000.0 for v in f[5:8])   # metres -> km
        recs.append((mjd, sod, x, y, z))
    if not recs:
        raise SystemExit("no type 10 position records in %s" % src)

    if t_from is not None:
        recs = [r for r in recs if mjd_to_datetime(r[0], r[1]) >= t_from]
    if hours is not None and recs:
        end = mjd_to_datetime(recs[0][0], recs[0][1]) + \
            datetime.timedelta(hours=hours)
        recs = [r for r in recs if mjd_to_datetime(r[0], r[1]) <= end]

    # Keep two extra records at each end: the velocity comes from a five-point
    # central difference, so the first and last two rows have no derivative.
    recs = recs[::step]
    if len(recs) < 9:
        raise SystemExit("only %d records after --step/--from; need at least 9"
                         % len(recs))

    dt = (recs[1][0] - recs[0][0]) * 86400.0 + (recs[1][1] - recs[0][1])

    eci = []
    for mjd, sod, x, y, z in recs:
        mjd_full = "%.15f" % (mjd + (sod + time_bias) / 86400.0)
        out = subprocess.run(
            [BIN, "%.6f" % x, "%.6f" % y, "%.6f" % z, "0", "0", "0", mjd_full],
            capture_output=True, text=True, cwd=BINDIR)
        line = [l for l in out.stdout.splitlines() if l.startswith("ECI:")]
        if not line:
            raise SystemExit("ECEF2ECI gave no answer at MJD %s:\n%s"
                             % (mjd_full, out.stdout + out.stderr))
        v = [float(t) for t in line[0].split()[1:4]]
        eci.append((mjd, sod, v[0], v[1], v[2]))

    rows = []
    for i in range(2, len(eci) - 2):
        # Five-point central difference; at a 5 minute grid this is good to
        # about a millimetre per second for a low Earth orbit.
        vel = []
        for k in range(2, 5):
            vel.append((eci[i - 2][k] - 8 * eci[i - 1][k] + 8 * eci[i + 1][k] -
                        eci[i + 2][k]) / (12.0 * dt))
        t = mjd_to_datetime(eci[i][0], eci[i][1])
        rows.append("%3d %5d %3d %3d %3d %3d %10.6f %17.6f %17.6f %17.6f "
                    "%17.9f %17.9f %17.9f"
                    % (sat_id, t.year, t.month, t.day, t.hour, t.minute,
                       t.second + t.microsecond * 1e-6,
                       eci[i][2], eci[i][3], eci[i][4], vel[0], vel[1], vel[2]))

    with open(dst, "w") as fh:
        fh.write("\n".join(rows) + "\n")

    print("%d states -> %s   (%.0f s grid)" % (len(rows), dst, dt))
    print("  first: %s" % rows[0][:70].strip())
    print("  config block for the first state:")
    f = rows[0].split()
    print("    t0                  = %s,%02d,%02d,%02d,%02d,%s"
          % (f[1], int(f[2]), int(f[3]), int(f[4]), int(f[5]), f[6]))
    for name, val in zip(("x0", "y0", "z0", "u0", "v0", "w0"), f[7:13]):
        print("    %-20s= %s" % (name, val))


if __name__ == "__main__":
    main(sys.argv)
