// forcemodel_comparator_header.cpp — the data the finite-difference gate's EXTENDED-PRECISION comparator needs (SPEC-forcemodel.md §6.2 (e)): the harmonic polynomials of degrees 2 - 4, exactly, and the
// constants of the registered truncation bound.
//
// Plan L0 step 8, group C7, ported to C++ (the user's directive of 2026-10-06) from tools/forcemodel_comparator_header.py, on tools/gradient_reference.cpp's exact polynomials, tools/forcemodel_fd_sizing.cpp's
// Phi and the devkit's Decimal.
//
// THE COMPARATOR (tests/fd_gate_tests.cpp) evaluates a plugin's acceleration in x87 `long double` from INDEPENDENT FORMULAS: each coefficient's potential is a homogeneous harmonic polynomial q over a power of
// r (the definition, by exact algebra: gradient_reference), so
//
//     a_i = GM a_e^n N_nm [ (d_i q) r^-(2n+1) - (2n+1) q x_i r^-(2n+3) ]
//
// with no Legendre recursion, no scaling, no Horner nest -- nothing the production synthesis uses.  Every polynomial coefficient is a dyadic rational with a small numerator, so it is EXACT in a double and in
// a long double; N_nm is the one square root, printed to 24 digits.
//
// ALSO EMITTED: Phi_nm of tools/forcemodel_fd_sizing.cpp (Lemma 2), so that the test recomputes the registered `F` from the coefficients and asserts it equals the frozen figure.
//
//   forcemodel_comparator_header [--header PATH] [--verify PATH]
//   exit 0 emitted / the committed header is what the generator emits   1 they differ   2 an argument error, or a file that cannot be read or written   70 an error the tool did not anticipate
//
// THE PROOF OF THE PORT.  The tool's product is a FILE, the generated header modules/forcemodel/tests/comparator_polynomials.hpp (5,499 bytes, 139 lines, one version in git since L7 step 1).  The port wrote
// it byte for byte, against a substitution list registered before the comparison and of TWO entries (the generator's own name in line 1, `tools/forcemodel_comparator_header.py` -> `.cpp`, and the name of
// the sizing tool in line 15, `(tools/forcemodel_fd_sizing.py)` -> `(tools/forcemodel_fd_sizing.cpp)`).  (C7_proof_registration.txt, in this group's report files, holds the registration and the results.)
//
// WHERE THE PORT DIFFERS, deliberately and said again at the place:
//   * The Python's assert that every coefficient is exact in a double is a refusal here (exit 1, the message the tuple of the assert: the coefficient and where it stands), as an uncaught AssertionError was.
//   * The Python's argparse took any unambiguous abbreviation of an option; here the names are exact (`--opt=value` is taken).  `-h` prints this tool's own text.  A file that is not UTF-8, a directory, a path
//     that cannot be written: REFUSED, exit 2, naming it (the Python died with a traceback, whose exit status 1 is the one it also used for "the header differs").  Text read back is compared as Python's
//     read_text() hands it back: universal newlines.  The path of `--header` is echoed as given.

#include <odl/devkit/decimal.hpp>
#include <odl/devkit/fs.hpp>
#include <odl/devkit/pyfmt.hpp>
#include <odl/devkit/pytext.hpp>
#include <odl/devkit/tool.hpp>

#include "forcemodel_comparator_header.hpp"
#include "forcemodel_fd_sizing.hpp"

#include <algorithm>
#include <iostream>

namespace dk = odl::devkit;

namespace odl::tools::forcemodel_comparator_header {

using dk::Decimal;
using dk::DecimalContext;
using dk::LocalContext;
using dk::Streams;
using odl::tools::gradient_reference::Poly;
using odl::tools::gradient_reference::Rational;

namespace {

constexpr int kOk = 0;
constexpr int kFailed = 1;
constexpr int kArgument = 2;
constexpr int kInternal = 70;
constexpr const char kTool[] = "forcemodel_comparator_header";

/// float(c) == c: the value is a double.
bool is_exact_double(const Rational& c) {
    try {
        return odl::tools::gradient_reference::rational_from_double(c.to_double()) == c;
    } catch (const std::range_error&) {
        return false;   // float(c) of a value no double can be near raises OverflowError
    }
}

std::string repr_fraction(const Rational& c) { return "Fraction(" + c.numerator().to_decimal() + ", " + c.denominator().to_decimal() + ")"; }

}  // namespace

std::string hexf_exact(const Rational& x) {
    if (!is_exact_double(x)) throw InexactCoefficient("not exact in a double: " + repr_fraction(x));
    return dk::py_float_hex(x.to_double());
}

std::string build(int nmax, const std::function<Poly(int, int, char)>& solid) {
    std::string text;
    const auto line = [&](const std::string& s) {
        text += s;
        text += '\n';
    };
    line("// GENERATED by tools/forcemodel_comparator_header.cpp — do not edit.");
    line("//");
    line("// The extended-precision comparator's data (SPEC-forcemodel.md §6.2 (e)): for each coefficient (n, m, kind) of degrees 2 – 4 the exact");
    line("// harmonic polynomial q, whose potential is GM a_e^n N_nm q / r^(2n+1), with N_nm and the registered bound's Phi_nm.  Each monomial");
    line("// coefficient is a dyadic rational, exact in a double; N_nm is printed to 24 digits for a long double.");
    line("#pragma once");
    line("");
    line("namespace odl::forcemodel::comparator {");
    line("");
    line("struct Monomial { int i, j, k; double c; };");
    line("struct Harmonic {");
    line("    int n, m;");
    line("    char kind;                 ///< 'C' or 'S'");
    line("    long double norm;          ///< N_nm, TN36-6 (6.2b)");
    line("    double phi;                ///< Lemma 2's Phi_nm (tools/forcemodel_fd_sizing.cpp)");
    line("    const Monomial* q;");
    line("    int terms;");
    line("};");
    line("");
    struct Entry {
        int n;
        int m;
        char kind;
        std::string norm_text;
        double phi;
        std::string name;
        std::size_t count;
    };
    std::vector<Entry> table;
    for (int n = 2; n <= nmax; ++n) {
        for (int m = 0; m <= n; ++m) {
            for (const char kind : {'C', 'S'}) {
                if (m == 0 && kind == 'S') continue;
                const Poly q = solid(n, m, kind);
                const std::string name = "kQ_" + std::to_string(n) + "_" + std::to_string(m) + "_" + std::string(1, kind);
                std::vector<Poly::Term> items = q.terms();
                std::sort(items.begin(), items.end(), [](const Poly::Term& a, const Poly::Term& b) { return a.first < b.first; });
                line("inline constexpr Monomial " + name + "[] = {");
                for (const Poly::Term& term : items) {
                    // a dyadic rational: exact as a double
                    if (!is_exact_double(term.second)) {
                        throw InexactCoefficient("(" + std::to_string(n) + ", " + std::to_string(m) + ", '" + std::string(1, kind) + "', " + std::to_string(term.first[0]) + ", " + std::to_string(term.first[1]) +
                                                 ", " + std::to_string(term.first[2]) + ", " + repr_fraction(term.second) + ")");
                    }
                    line("    {" + std::to_string(term.first[0]) + ", " + std::to_string(term.first[1]) + ", " + std::to_string(term.first[2]) + ", " + dk::py_float_hex(term.second.to_double()) + "},");
                }
                line("};");
                std::string norm_text;
                {
                    LocalContext ctx(40);
                    const Rational nsq = odl::tools::gradient_reference::norm_squared(n, m);
                    const Decimal norm = (Decimal(nsq.numerator()) / Decimal(nsq.denominator())).sqrt();
                    norm_text = norm.format(".24f");
                }
                table.push_back(Entry{n, m, kind, norm_text, odl::tools::forcemodel_fd_sizing::phi(n, m, kind), name, items.size()});
            }
        }
    }
    line("");
    line("inline constexpr Harmonic kHarmonics[] = {");
    for (const Entry& e : table) {
        line("    {" + std::to_string(e.n) + ", " + std::to_string(e.m) + ", '" + std::string(1, e.kind) + "', " + e.norm_text + "L, " + dk::py_float_hex(e.phi) + ", " + e.name + ", " + std::to_string(e.count) + "},");
    }
    line("};");
    line("");
    line("}  // namespace odl::forcemodel::comparator");
    return text;
}

namespace {

const char kUsageText[] = "usage: forcemodel_comparator_header [-h] [--header HEADER] [--verify VERIFY]\n";

const char kHelpText[] =
    "\n"
    "The data the finite-difference gate's extended-precision comparator needs (SPEC-forcemodel.md §6.2 (e)): the harmonic polynomials of degrees 2 - 4, exactly, and the constants of the registered\n"
    "truncation bound (the header modules/forcemodel/tests/comparator_polynomials.hpp).\n"
    "\n"
    "options:\n"
    "  -h, --help       show this help and exit\n"
    "  --header HEADER  write a C++ header here instead of printing\n"
    "  --verify VERIFY  compare this committed header with what the generator emits; exit 1 if they differ\n"
    "\n"
    "exit codes: 0 emitted / the committed header is what the generator emits   1 they differ, or a coefficient is not exact in a double\n"
    "            2 an argument error, or a file that cannot be read or written\n";

}  // namespace

int run_on(const std::function<Poly(int, int, char)>& solid, const std::vector<std::string>& argv, Streams io) {
    try {
        std::string header_given;
        std::string verify_given;
        bool has_header = false;
        bool has_verify = false;
        const auto usage_error = [&](const std::string& what) {
            io.err << kUsageText << kTool << ": error: " << what << '\n';
            return kArgument;
        };
        for (std::size_t i = 0; i < argv.size(); ++i) {
            std::string opt = argv[i];
            std::string value;
            bool has_value = false;
            const std::size_t eq = opt.find('=');
            if (opt.rfind("--", 0) == 0 && eq != std::string::npos) {
                value = opt.substr(eq + 1);
                opt = opt.substr(0, eq);
                has_value = true;
            }
            if (opt == "-h" || opt == "--help") {
                io.out << kUsageText << kHelpText;
                return kOk;
            }
            if (opt == "--header" || opt == "--verify") {
                if (!has_value) {
                    if (i + 1 >= argv.size() || argv[i + 1].rfind("--", 0) == 0) return usage_error("argument " + opt + ": expected one argument");
                    value = argv[++i];
                }
                if (opt == "--header") {
                    header_given = value;
                    has_header = true;
                } else {
                    verify_given = value;
                    has_verify = true;
                }
            } else {
                return usage_error("unrecognized arguments: " + argv[i]);
            }
        }

        // the Python's own state: the default decimal context
        LocalContext fresh;
        fresh.context() = DecimalContext{};

        std::string text;
        try {
            text = build(kNmax, solid);
        } catch (const InexactCoefficient& exc) {
            io.err << kTool << ": " << exc.what() << '\n';
            return kFailed;
        }
        if (has_verify) {
            std::string committed;
            try {
                committed = dk::universal_newlines(dk::read_text(verify_given));
            } catch (const std::runtime_error& exc) {
                io.err << kTool << ": " << exc.what() << '\n';
                return kArgument;
            }
            const bool ok = committed == text;
            io.err << (ok ? "ok       the committed header is exactly what the generator emits" : "MISMATCH the committed header differs from the generator's output") << '\n';
            return ok ? kOk : kFailed;
        }
        if (has_header) {
            try {
                dk::write_text(header_given, text);
            } catch (const std::runtime_error& exc) {
                io.err << kTool << ": " << exc.what() << '\n';
                return kArgument;
            }
            io.err << "wrote " << std::count(text.begin(), text.end(), '\n') << " lines to " << header_given << '\n';
        } else {
            io.out << text << '\n';
        }
        return kOk;
    } catch (const std::exception& exc) {
        io.err << kTool << ": internal error: " << exc.what() << '\n';
        return kInternal;
    }
}

int run(const std::vector<std::string>& argv, Streams io) { return run_on(odl::tools::gradient_reference::solid_polynomial, argv, io); }

}  // namespace odl::tools::forcemodel_comparator_header

#ifndef ODL_TOOL_NO_MAIN
int main(int argc, char** argv) {
    std::vector<std::string> args(argv + 1, argv + argc);
    return odl::tools::forcemodel_comparator_header::run(args, odl::devkit::Streams{std::cout, std::cerr});
}
#endif
