#!/usr/bin/env python3
"""forcemodel_comparator_header.py — the data the finite-difference gate's EXTENDED-PRECISION comparator needs
(SPEC-forcemodel.md §6.2 (e)): the harmonic polynomials of degrees 2 – 4, exactly, and the constants of the registered truncation bound.

THE COMPARATOR (tests/fd_gate_tests.cpp) evaluates a plugin's acceleration in x87 `long double` from INDEPENDENT FORMULAS: each coefficient's
potential is a homogeneous harmonic polynomial q over a power of r (the definition, by exact algebra: gradient_reference.py), so

    a_i = GM a_e^n N_nm [ (d_i q) r^-(2n+1) - (2n+1) q x_i r^-(2n+3) ]

with no Legendre recursion, no scaling, no Horner nest — nothing the production synthesis uses.  Every polynomial coefficient is a dyadic
rational with a small numerator, so it is EXACT in a double and in a long double; N_nm is the one square root, printed to 24 digits.

ALSO EMITTED: Phi_nm of tools/forcemodel_fd_sizing.py (Lemma 2), so that the test recomputes the registered `F` from the coefficients and asserts
it equals the frozen figure.

Usage:  forcemodel_comparator_header.py [--header PATH] [--verify PATH]
Exit:   0 emitted / the committed header is what the generator emits   1 they differ
"""
from __future__ import annotations

import argparse
import sys
from decimal import Decimal, localcontext
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import forcemodel_fd_sizing as fd   # noqa: E402
import gradient_reference as gr     # noqa: E402

NMAX = 4


def hexf(x) -> str:
    return float(x).hex()


def build() -> str:
    lines = [
        "// GENERATED by tools/forcemodel_comparator_header.py — do not edit.",
        "//",
        "// The extended-precision comparator's data (SPEC-forcemodel.md §6.2 (e)): for each coefficient (n, m, kind) of degrees 2 – 4 the exact",
        "// harmonic polynomial q, whose potential is GM a_e^n N_nm q / r^(2n+1), with N_nm and the registered bound's Phi_nm.  Each monomial",
        "// coefficient is a dyadic rational, exact in a double; N_nm is printed to 24 digits for a long double.",
        "#pragma once",
        "",
        "namespace odl::forcemodel::comparator {",
        "",
        "struct Monomial { int i, j, k; double c; };",
        "struct Harmonic {",
        "    int n, m;",
        "    char kind;                 ///< 'C' or 'S'",
        "    long double norm;          ///< N_nm, TN36-6 (6.2b)",
        "    double phi;                ///< Lemma 2's Phi_nm (tools/forcemodel_fd_sizing.py)",
        "    const Monomial* q;",
        "    int terms;",
        "};",
        "",
    ]
    table = []
    for n in range(2, NMAX + 1):
        for m in range(n + 1):
            for kind in "CS":
                if m == 0 and kind == "S":
                    continue
                q = gr.solid_polynomial(n, m, kind)
                name = f"kQ_{n}_{m}_{kind}"
                items = sorted(q.items())
                lines.append(f"inline constexpr Monomial {name}[] = {{")
                for (i, j, k), c in items:
                    # a dyadic rational: exact as a double
                    assert float(c) == c, (n, m, kind, i, j, k, c)
                    lines.append(f"    {{{i}, {j}, {k}, {hexf(c)}}},")
                lines.append("};")
                with localcontext() as ctx:
                    ctx.prec = 40
                    nsq = gr.norm_squared(n, m)
                    norm = (Decimal(nsq.numerator) / Decimal(nsq.denominator)).sqrt()
                    norm_text = f"{norm:.24f}"
                table.append((n, m, kind, norm_text, fd.phi(n, m, kind), name, len(items)))
    lines.append("")
    lines.append("inline constexpr Harmonic kHarmonics[] = {")
    for n, m, kind, norm_text, phi, name, count in table:
        lines.append(f"    {{{n}, {m}, '{kind}', {norm_text}L, {hexf(phi)}, {name}, {count}}},")
    lines.append("};")
    lines.append("")
    lines.append("}  // namespace odl::forcemodel::comparator")
    lines.append("")
    return "\n".join(lines)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(prog="forcemodel_comparator_header.py", description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--header", type=Path, default=None)
    ap.add_argument("--verify", type=Path, default=None)
    args = ap.parse_args(argv)
    text = build()
    if args.verify:
        ok = args.verify.read_text(encoding="utf-8") == text
        print("ok       the committed header is exactly what the generator emits" if ok
              else "MISMATCH the committed header differs from the generator's output", file=sys.stderr)
        return 0 if ok else 1
    if args.header:
        args.header.write_text(text, encoding="utf-8")
        print(f"wrote {len(text.splitlines())} lines to {args.header}", file=sys.stderr)
    else:
        print(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
