#!/usr/bin/env python3
"""legendre_reference.py — reference values for GRAV-A-003, from the DEFINITION.

SPEC-gravity §4.4's recursion is derived from TN36-6 (6.2b) with DLMF 14.6 and
14.10, and GRAV-A-003 checks the double-precision implementation of it against
the definition evaluated in at least 50-digit arithmetic.  This produces those
values.  It must not use the recursion, or the test would compare the
implementation with itself.

THE DEFINITION, with no Condon-Shortley phase (GRAV-R-007):

    P_n^m(x) = (1 - x^2)^(m/2) d^m/dx^m P_n(x)

    P_n(x) = 2^-n sum_j (-1)^j C(n,j) C(2n-2j, n) x^(n-2j)

so, differentiating m times and dividing out the (1 - x^2)^(m/2) that
SPEC-gravity factors away,

    Pbar'_nm(u) = N_nm 2^-n sum_j (-1)^j C(n,j) C(2n-2j,n) (n-2j)!/(n-2j-m)! u^(n-2j-m)

over j with n - 2j - m >= 0, and N_nm from TN36-6 (6.2b).

WHY THE PRECISION IS SET SO HIGH.  The terms of that sum reach about 2^n/sqrt(pi n)
— at n = 2190, some 10^659 — and cancel down to a result of order 10.  Roughly
660 digits are destroyed by cancellation before the answer appears, so 50 digits
of output needs well over 700 of working precision.  Nothing warns you about
this: at 50 digits the sum returns confident nonsense.  The guard is that this
tool computes every value at two precisions and refuses to emit any value whose
two evaluations disagree.

Usage:  legendre_reference.py [--check] [--header PATH]
Exit:   0 emitted   1 a value failed its two-precision agreement check
"""

from __future__ import annotations

import argparse
import sys
from decimal import Decimal, getcontext, localcontext
from fractions import Fraction
from math import comb, factorial
from pathlib import Path

# (n, m) pairs, chosen to span the model: low degrees with closed forms, the
# sectorial and zonal extremes at full degree, and the interior.
POINTS = [(2, 0), (2, 1), (2, 2), (4, 3), (10, 7), (60, 30), (360, 360),
          (1000, 500), (1500, 1499), (2190, 0), (2190, 1), (2190, 1095), (2190, 2190)]

# sin(phi) values.  0 is the equator; the last is close enough to the pole that
# the unfactored function has underflowed a double for every order above 176.
SINES = ["0", "0.3971478906347806", "0.7071067811865476", "0.9396926207859084",
         "0.9999984769132877", "1"]


def norm_squared(n: int, m: int) -> Fraction:
    """N_nm^2 from TN36-6 (6.2b), exactly."""
    return Fraction(factorial(n - m) * (2 * n + 1) * (2 - (1 if m == 0 else 0)),
                    factorial(n + m))


def pbar_factored(n: int, m: int, u: str, precision: int) -> Decimal:
    with localcontext() as ctx:
        ctx.prec = precision
        x = Decimal(u)
        nsq = norm_squared(n, m)
        norm = (Decimal(nsq.numerator) / Decimal(nsq.denominator)).sqrt()
        total = Decimal(0)
        j = 0
        while n - 2 * j - m >= 0:
            e = n - 2 * j - m
            coeff = ((-1) ** j) * comb(n, j) * comb(2 * n - 2 * j, n) \
                * factorial(n - 2 * j) // factorial(e)
            total += Decimal(coeff) * (x ** e if e else Decimal(1))
            j += 1
        return +(norm * total / (Decimal(2) ** n))


def value(n: int, m: int, u: str) -> Decimal:
    """Evaluated twice, at different precisions, and refused if they disagree."""
    lo = 4 * n + 400
    hi = lo + 300
    a = pbar_factored(n, m, u, lo)
    b = pbar_factored(n, m, u, hi)
    getcontext().prec = 60
    a60, b60 = +a, +b
    if a == 0 and b == 0:
        return Decimal(0)
    if b60 == 0 or abs((a60 - b60) / b60) > Decimal("1e-50"):
        raise ValueError(f"Pbar'_{n},{m}(u={u}) does not agree between {lo} and {hi} digits: "
                         f"{a60} vs {b60}")
    return b60


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(prog="legendre_reference.py", description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--header", type=Path, default=None,
                    help="write a C++ header here instead of printing")
    args = ap.parse_args(argv)

    rows = []
    for n, m in POINTS:
        for u in SINES:
            if n == 0 and u == "1":
                pass
            try:
                v = value(n, m, u)
            except ValueError as exc:
                print(f"REFUSED  {exc}", file=sys.stderr)
                return 1
            rows.append((n, m, u, v))
            print(f"ok       Pbar'_{n},{m}(u={u}) = {v}", file=sys.stderr)

    lines = [
        "// GENERATED by tools/legendre_reference.py — do not edit.",
        "//",
        "// Reference values for GRAV-A-003, computed from the DEFINITION of the",
        "// associated Legendre function in high-precision decimal arithmetic, never",
        "// from SPEC-gravity §4.4's recursion.  A test whose reference came from the",
        "// same recursion it is testing would pass for a recursion that is wrong.",
        "//",
        "// Each value was evaluated at two precisions and is emitted only if the two",
        "// agree to 50 significant digits; at degree 2190 about 660 digits are lost to",
        "// cancellation before the answer appears, and a naive 50-digit evaluation",
        "// returns confident nonsense rather than failing.",
        "#pragma once",
        "",
        "namespace odl::gravity::reference {",
        "",
        "// Most of these values do not fit in a double: max over m of",
        "// Pbar'_{2190,m}(1) is 10^457.864, which is 10^150 past the largest double.",
        "// So each row carries BOTH the direct value, where there is one, and the",
        "// base-10 logarithm of its magnitude with its sign, which there always is.",
        "// A row with representable = false is checked through the scaled path, not",
        "// skipped: the values that do not fit are exactly the ones worth checking.",
        "struct LegendreValue {",
        "    int n;",
        "    int m;",
        "    double sin_phi;",
        "    bool representable;",
        "    double pbar_factored;   ///< Pbar_nm(sin phi) / cos^m(phi), or 0 if it does not fit",
        "    double log10_abs;       ///< log10 |Pbar'_nm|, or 0 when the value is 0",
        "    double sign;            ///< +1, -1 or 0",
        "};",
        "",
        "inline constexpr LegendreValue kLegendre[] = {",
    ]
    for n, m, u, v in rows:
        if v == 0:
            lines.append(f"    {{{n}, {m}, {u}, true, 0.0, 0.0, 0.0}},")
            continue
        sign = 1 if v > 0 else -1
        with localcontext() as ctx:
            ctx.prec = 80
            l10 = abs(v).log10()
        fits = Decimal("-300") < l10 < Decimal("300")
        direct = f"{v:.17e}" if fits else "0.0"
        lines.append(f"    {{{n}, {m}, {u}, {'true' if fits else 'false'}, {direct}, "
                     f"{l10:.17f}, {sign}.0}},")
    lines += ["};", "", "}  // namespace odl::gravity::reference", ""]
    text = "\n".join(lines)
    if args.header:
        args.header.write_text(text, encoding="utf-8")
        print(f"\nwrote {len(rows)} values to {args.header}", file=sys.stderr)
    else:
        print(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
