#!/usr/bin/env python3
"""msis_reference.py — freeze the NRLMSISE-00 reference implementation's output.

SPEC-atmosphere ATMO-R-028.  The gate must run offline from the cache and with
no Fortran compiler, so the reference's output is committed as generated source
and `ATMO-A-001` compares against that.  Where a compiler IS present this tool
regenerates the file and the suite diffs it, so the frozen artefact is itself
under test rather than trusted.

WHY THIS TOOL EXISTS AT ALL, which is the whole of step 4's finding: NRL
publishes NO reference value for NRLMSISE-00.  The distribution's test driver
publishes 17 fully specified INPUT cases and no expected output; the archive
tables publish output statistics against a database NRL does not ship.  The
reference implementation is therefore normative rather than an oracle — plan §4
rule 6 — and its output on its own published inputs is a category-1 acceptance
value.  What that cannot check is stated in SPEC-atmosphere §8.

THE PUBLISHED DRIVER'S OWN OUTPUT IS NOT ENOUGH.  It prints `1P8E9.2` — three
significant figures — and its summary table four, against a model whose own
value is defined to about six (§3.2).  So this tool replicates the driver's
`DATA` statements EXACTLY and changes only the output FORMAT.

The reference source is NOT edited.  `-fdec-char-conversions` exists because
three DATA statements at lines 1670-1671 use the FORTRAN 66 Hollerith idiom for
the model's output header stamp, which touches no arithmetic.
"""
from __future__ import annotations
import argparse, hashlib, json, shutil, subprocess, sys, textwrap
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FOR_ID = "nrlmsise00-fortran"
DRIVER_SPLIT = 2437          # the model is lines 1..2437; the driver follows
FLAGS = ["-std=legacy", "-fdec-char-conversions", "-O0"]
PROMOTE = "-freal-4-real-8"  # same source, every REAL widened: isolates precision artefacts

# The sweep.  Chosen to cross EVERY branch boundary the model has (SPEC-atmosphere
# §3.6): ZN3 nodes 0/10/15/20/32.5, ZN2 45/55/72.5, ZMIX 62.5, ZN1 90/100/110/120,
# and the analytic Bates profile above.  A sweep that never crosses a boundary
# cannot fail on a boundary.
#
# ABOVE 120 KM, "no structural boundary" (SPEC-atmosphere §3.1's own former
# text) was itself a claim that had never been searched for in the source --
# L4 step 4's own drag Jacobian found the 300 km one by measurement, and a
# direct read of the pinned NRLMSISE-00.FOR's DATA ALTL (line 587) found the
# other six: N2 160, He 200, Ar 240, O2 250, O 300, H 320, N 450 km, each a
# species-correction cutoff and each a genuine discontinuity (confirmed: the
# reference jumps identically to the port at every one, to full double
# precision -- PROVENANCE.md §28.5/§28.10). 200 and 300 already sat in the
# coarse grid above without being fine enough to straddle either cutoff by
# more than a few metres; CUTOFF_STRADDLE adds a close pair either side of
# all seven, so the sweep that is supposed to cross every boundary the model
# has actually crosses these, rather than landing near them and calling that
# coverage.
CUTOFF_STRADDLE_KM = [160.0, 200.0, 240.0, 250.0, 300.0, 320.0, 450.0]
SWEEP_ALT = [0.0, 5.0, 10.0, 15.0, 20.0, 25.0, 32.5, 40.0, 45.0, 55.0, 62.5, 70.0,
             72.5, 80.0, 90.0, 100.0, 110.0, 120.0, 150.0, 200.0, 300.0, 400.0,
             550.0, 700.0, 1000.0, 1500.0, 2000.0] + [
    round(c + offset_m / 1000.0, 6) for c in CUTOFF_STRADDLE_KM for offset_m in (-10.0, 10.0)
]
SWEEP_COND = [  # iday,  sec,   lat,   lon, f107a, f107,  ap
    (172,  29000.0,  60.0, -70.0, 150.0, 150.0,   4.0),   # the driver's baseline
    ( 81,  29000.0,   0.0,   0.0,  70.0,  70.0,   0.0),   # equinox, equator, solar minimum, quiet
    (355,  75000.0, -80.0, 170.0, 250.0, 300.0, 200.0),   # southern winter, solar max, severe storm
    (200,  43200.0,  45.0,  90.0, 100.0,  90.0,  15.0),   # mid-latitude, moderate
]

def find_source() -> Path:
    doc = json.loads((ROOT / "manifest" / "manifest.json").read_text())
    e = next(x for x in doc["entries"] if x["id"] == FOR_ID)
    p = ROOT / doc["cache"] / e["id"] / e["filename"]
    got = hashlib.sha256(p.read_bytes()).hexdigest()
    if got != e["sha256"]:
        sys.exit(f"{FOR_ID}: cached bytes are not the pinned bytes\n  want {e['sha256']}\n  got  {got}")
    return p

def driver_source() -> str:
    """The 17 published cases verbatim, then a sweep read from stdin."""
    return textwrap.dedent("""\
    C     GENERATED by tools/msis_reference.py -- do not edit.
    C     Part 1 replicates NRLMSISE-00.FOR lines 2438-2552's DATA statements
    C     EXACTLY; only the output FORMAT differs.  Part 2 reads a sweep.
          DIMENSION D(9),T(2),SW(25),SWD(25),APH(7)
          DIMENSION IDAY(15),UT(15),ALT(15),XLAT(15),XLONG(15),XLST(15),
         & F107A(15),F107(15),AP(15)
          DATA IDAY/172,81,13*172/
          DATA UT/29000.,29000.,75000.,12*29000./
          DATA ALT/400.,400.,1000.,100.,6*400.,0,10.,30.,50.,70./
          DATA XLAT/4*60.,0.,10*60./
          DATA XLONG/5*-70.,0.,9*-70./
          DATA XLST/6*16.,4.,8*16./
          DATA F107A/7*150.,70.,7*150./
          DATA F107/8*150.,180.,6*150./
          DATA AP/9*4.,40.,5*4./
          DATA APH/7*100./,SW/8*1.,-1.,16*1./,SWD/25*1./
          DO I=1,15
             CALL GTD7(IDAY(I),UT(I),ALT(I),XLAT(I),XLONG(I),XLST(I),
         &             F107A(I),F107(I),AP(I),48,D,T)
             CALL WROUT('P',I,D,T)
             CALL GTD7D(IDAY(I),UT(I),ALT(I),XLAT(I),XLONG(I),XLST(I),
         &             F107A(I),F107(I),AP(I),48,D,T)
             CALL WRRHO('P',I,D(6))
          ENDDO
          CALL TSELEC(SW)
          CALL GTD7(IDAY(1),UT(1),ALT(1),XLAT(1),XLONG(1),XLST(1),
         &             F107A(1),F107(1),APH,48,D,T)
          CALL WROUT('P',16,D,T)
          CALL GTD7D(IDAY(1),UT(1),ALT(1),XLAT(1),XLONG(1),XLST(1),
         &             F107A(1),F107(1),APH,48,D,T)
          CALL WRRHO('P',16,D(6))
          CALL GTD7(IDAY(1),UT(1),ALT(4),XLAT(1),XLONG(1),XLST(1),
         &             F107A(1),F107(1),APH,48,D,T)
          CALL WROUT('P',17,D,T)
          CALL GTD7D(IDAY(1),UT(1),ALT(4),XLAT(1),XLONG(1),XLST(1),
         &             F107A(1),F107(1),APH,48,D,T)
          CALL WRRHO('P',17,D(6))
    C     ---- part 2: the sweep, one case per line on stdin ----
          CALL TSELEC(SWD)
          READ(5,*) NS
          DO K=1,NS
             READ(5,*) JD,SEC,ZALT,GLAT,GLON,STL,FA,FD,APD
             CALL GTD7(JD,SEC,ZALT,GLAT,GLON,STL,FA,FD,APD,48,D,T)
             CALL WROUT('S',K,D,T)
             CALL GTD7D(JD,SEC,ZALT,GLAT,GLON,STL,FA,FD,APD,48,D,T)
             CALL WRRHO('S',K,D(6))
          ENDDO
          END
          FUNCTION SW2()
          DIMENSION SW2(25)
          DO J=1,25
             SW2(J)=1.
          ENDDO
          END
          SUBROUTINE WROUT(TAG,I,D,T)
          CHARACTER*1 TAG
          DIMENSION D(9),T(2)
          WRITE(6,100) TAG,I,(D(J),J=1,9),T(1),T(2)
      100 FORMAT('G7 ',A1,I5,11(1X,1PE25.17))
          END
          SUBROUTINE WRRHO(TAG,I,R)
          CHARACTER*1 TAG
          WRITE(6,101) TAG,I,R
      101 FORMAT('G7D ',A1,I5,1X,1PE25.17)
          END
    """)

def build(src: Path, work: Path, promoted: bool) -> Path:
    model = work / "model.f"
    model.write_text("\n".join(src.read_text(errors="replace").split("\n")[:DRIVER_SPLIT]) + "\n")
    drv = work / "driver.f"; drv.write_text(driver_source())
    exe = work / ("ref_d" if promoted else "ref_s")
    cmd = [GFORTRAN, *FLAGS] + ([PROMOTE] if promoted else []) + ["-o", str(exe), str(model), str(drv)]
    r = subprocess.run(cmd, capture_output=True, text=True)
    if r.returncode:
        sys.exit("gfortran failed:\n" + r.stderr[-2000:])
    return exe

def run(exe: Path) -> dict:
    lines = [f"{len(SWEEP_ALT)*len(SWEEP_COND)}"]
    for (jd, sec, lat, lon, fa, fd, ap) in SWEEP_COND:
        for alt in SWEEP_ALT:
            stl = sec / 3600.0 + lon / 15.0
            lines.append(f"{jd} {sec} {alt} {lat} {lon} {stl} {fa} {fd} {ap}")
    r = subprocess.run([str(exe)], input="\n".join(lines) + "\n", capture_output=True, text=True)
    if r.returncode:
        sys.exit(f"reference run failed: {r.stderr[-1000:]}")
    out = {}
    for L in r.stdout.split("\n"):
        p = L.split()
        if not p: continue
        if p[0] == "G7":    out[("g7",  p[1], int(p[2]))] = [float(x) for x in p[3:]]
        elif p[0] == "G7D": out[("g7d", p[1], int(p[2]))] = [float(p[3])]
    return out

def main() -> int:
    global GFORTRAN
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default="modules/atmosphere/src/msis_reference_values.hpp")
    ap.add_argument("--check", action="store_true", help="regenerate and diff, do not write")
    a = ap.parse_args()
    GFORTRAN = next((c for c in ("gfortran", "gfortran-16", "gfortran-15", "gfortran-14", "gfortran-13")
                     if shutil.which(c)), None)
    if not GFORTRAN:
        print("no Fortran compiler on PATH; nothing regenerated (ATMO-R-028: the gate does not need one)")
        return 0
    ver = subprocess.run([GFORTRAN, "--version"], capture_output=True, text=True).stdout.split("\n")[0]
    src = find_source()
    sha = hashlib.sha256(src.read_bytes()).hexdigest()
    work = Path(__file__).parent / ".msisref"; work.mkdir(exist_ok=True)
    single = run(build(src, work, False))
    double = run(build(src, work, True))

    # The threshold-sensitivity claim (class A's worst barely moves across
    # three decades of the materiality threshold) is measured here, each
    # time, rather than quoted from whenever it was last checked by hand.
    sensitivity = {t: classify(single, double, t)[0][0][0] for t in (1e-12, 1e-15, 1e-20)}
    text = emit(ver, sha, *classify(single, double), double, single, sensitivity)
    out = ROOT / a.out
    if a.check:
        cur = out.read_text() if out.exists() else ""
        if cur != text:
            print("REGENERATED OUTPUT DIFFERS from the committed file", file=sys.stderr); return 1
        print(f"ok  {a.out} reproduces from {FOR_ID} with {GFORTRAN}")
        return 0
    out.write_text(text)
    mat, immat, under, zeros = classify(single, double)
    print(f"wrote {a.out}: {len(double)//2} reference records; comparisons "
          f"material {len(mat)}, immaterial {len(immat)}, underflowed {len(under)}, zero {zeros}")
    return 0

AMU = 1.66e-24
SPECIES_MASS = {0: 4.0, 1: 16.0, 2: 28.0, 3: 32.0, 4: 40.0, 6: 1.0, 7: 14.0, 8: 16.0}
SPECIES_NAME = {0: "He", 1: "O", 2: "N2", 3: "O2", 4: "Ar", 5: "rho", 6: "H", 7: "N",
                8: "anomalous O", 9: "Tinf", 10: "T(alt)"}
MATERIAL = 1e-15   # see classify()


def describe(k) -> str:
    """A worst-comparison key (kind, set, index) as a human-readable place,
    computed from the SAME loop order run() used to build it -- not
    hardcoded, so this description cannot go stale the way a literal
    string did the first time the sweep grew (msis_reference_values.hpp's
    own history, PROVENANCE.md §28.5/§28.10)."""
    _, set_, idx = k
    if set_ == "P":
        return f"published case {idx}"
    n = (idx - 1) % len(SWEEP_ALT)
    c = (idx - 1) // len(SWEEP_ALT)
    jd, sec, lat, lon, fa, fd, ap = SWEEP_COND[c]
    return f"sweep alt {SWEEP_ALT[n]:g} km, condition ({jd:g},{sec:g},{lat:g},{lon:g},{fa:g},{fd:g},{ap:g})"


def classify(single: dict, double: dict, material: float = MATERIAL):
    """Partition every comparison by whether it can affect a drag calculation.

    THE SWEEP CHANGED THE SHAPE OF THIS MEASUREMENT.  Over the 17 published cases
    the reference's single-precision artefact looks like one number: median 4e-7,
    worst 8e-6.  Over a sweep that crosses every branch boundary it does not —
    the worst relative difference is 7.9e-3, a thousand times larger.

    Every one of those large differences is a quantity of order 1e-30 to 1e-37:
    anomalous oxygen at 110 km, argon at 2000 km, hydrogen at 72.5 km.  Single
    precision's smallest normal is 1.18e-38, so these are values approaching the
    underflow boundary, losing significance continuously on the way down until
    they cross it and become the hard zeros of the underflow class.  It is ONE
    phenomenon in three regimes, not a tolerance with an exception bolted on.

    So the boundary is drawn PHYSICALLY rather than numerically: a species whose
    mass contributes less than MATERIAL of the total density cannot affect drag
    at any precision.  That threshold is not tuned — the worst material
    difference moves by less than a factor of 2 across three decades of it
    (1e-12, 1e-15, 1e-20; main() recomputes and emit() prints the current
    figures each time, rather than a number quoted here that could go stale
    the way the sweep's own growth once made one).  Stable across three
    decades is what distinguishes a principled boundary from a fitted one.
    """
    mat, immat, under, zeros = [], [], [], 0
    for k, dv in double.items():
        sv, rho = single[k], (dv[5] if k[0] == "g7" else dv[0])
        for j, (xs, xd) in enumerate(zip(sv, dv)):
            if xd == 0.0:
                zeros += 1; continue
            if xs == 0.0:
                under.append((k, j, xd)); continue
            r = abs(xs - xd) / abs(xd)
            frac = (SPECIES_MASS[j] * xd * AMU / rho) if (k[0] == "g7" and j in SPECIES_MASS) else 1.0
            (mat if frac >= material else immat).append((r, k, j))
    mat.sort(reverse=True); immat.sort(reverse=True)
    return mat, immat, under, zeros


def emit(ver, sha, mat, immat, under, zeros, double, single, sensitivity) -> str:
    med = mat[len(mat)//2][0]
    rel = mat
    L = []
    w = L.append

    def wc(text: str) -> None:
        for line in textwrap.wrap(text, width=77):
            w(f"// {line}")
    w("#pragma once")
    w("// msis_reference_values.hpp — GENERATED.  Do not edit.")
    w("//")
    w("// Produced by tools/msis_reference.py from the hash-pinned NRL reference")
    w(f"// implementation NRLMSISE-00.FOR, sha256 {sha}")
    w("//")
    w("// SPEC-atmosphere ATMO-R-028.  NRL PUBLISHES NO REFERENCE VALUE FOR THIS MODEL:")
    w("// its test driver publishes 17 fully specified INPUT cases and no expected")
    w("// output, and its archive tables are statistics against a database NRL does not")
    w("// ship.  The reference implementation is therefore NORMATIVE rather than an")
    w("// oracle (plan §4 rule 6), and these are its own values on its own published")
    w("// inputs.  What that cannot check is stated in SPEC-atmosphere §8: nothing here")
    w("// can tell whether the FORTRAN computes what the paper describes.")
    w("//")
    w("// THE RECIPE, so that this file is reproducible rather than merely present:")
    w(f"//   compiler : {ver}")
    w(f"//   flags    : {' '.join(FLAGS)}")
    w(f"//   promoted : {' '.join(FLAGS)} {PROMOTE}   (same source, every REAL widened)")
    w("//   source   : lines 1..2437 of the pinned file; the distribution's own driver")
    w("//              at 2438..2552 is replaced by one whose DATA statements are")
    w("//              IDENTICAL and whose output FORMAT is not -- the published driver")
    w("//              prints three significant figures against a model defined to six.")
    w("//   unedited : the reference source is not modified.  -fdec-char-conversions")
    w("//              accepts three FORTRAN 66 Hollerith DATA statements at lines")
    w("//              1670-1671 carrying the output header stamp and no arithmetic.")
    w("//   -O0      : deliberate.  Optimisation may reassociate single-precision")
    w("//              arithmetic and move the reference's own value by more than the")
    w("//              median artefact measured below.")
    w("//")
    tot = len(mat) + len(immat) + len(under) + zeros
    w("// THE TOLERANCE IS DERIVED HERE, not asserted elsewhere.  Single precision")
    w("// against the promoted-double build of the SAME source, every comparison")
    w("// classified by whether it can affect a drag calculation at all:")
    w("//")
    w(f"//   A  material     {len(mat):5d}   median {med:.4e}   worst {mat[0][0]:.4e}")
    w(f"//   B  immaterial   {len(immat):5d}                        worst {immat[0][0]:.4e}")
    w(f"//   C  underflowed  {len(under):5d}   single returned exactly zero, double did not")
    w(f"//   Z  zero in both {zeros:5d}   the documented zeros below 72.5 km, and anomalous O")
    w(f"//   total           {tot:5d}   = {len(double)//2} records x 12 quantities")
    w("//")
    w("// The reference is SINGLE PRECISION throughout (no DOUBLE PRECISION, no REAL*8,")
    w("// no .D0 anywhere in it), so its own value is uncertain and NO TOLERANCE MAY BE")
    w("// TIGHTER than class A's worst.  Classes B and C are not a tolerance question:")
    w("// they are quantities of order 1e-30 and below, approaching and then crossing")
    w("// single precision's smallest normal (1.18e-38), where a correct double port")
    w("// disagrees with the reference by up to 100% and is right to.  They are COUNTED,")
    w("// never absorbed into a widened tolerance -- the third time this tree has met a")
    w("// quantity that exists in one precision and not another.")
    w("//")
    wc(f"The class boundary is physical, not numerical: a species whose mass is less "
       f"than {MATERIAL:g} of the total density cannot affect drag.  It is not tuned -- "
       f"class A's worst is {sensitivity[1e-12]:.3e} at a threshold of 1e-12 and "
       f"{sensitivity[1e-15]:.3e} at 1e-15, and only {sensitivity[1e-20]:.3e} at 1e-20.")
    w("//")
    worst_species = SPECIES_NAME.get(mat[0][2], f"quantity {mat[0][2]}")
    p_material = sum(1 for _, k, _ in mat if k[1] == 'P')
    s_material = len(mat) - p_material
    worst_among_published = max((r for r, k, _ in mat if k[1] == 'P'), default=0.0)
    if mat[0][1][1] == 'P':
        wc(f"The worst class-A comparison is {worst_species} at {describe(mat[0][1])} -- "
           f"one of the 17 published cases: the {s_material} further material "
           f"comparisons the sweep adds, across every branch boundary, do NOT exceed it.")
    else:
        wc(f"The worst class-A comparison is {worst_species} at {describe(mat[0][1])} -- "
           f"a SWEEP point, not one of the 17 published cases (whose own worst is "
           f"{worst_among_published:.3e}). THE SWEEP DOES NOT MERELY FAIL TO LOOSEN THE "
           f"BOUND HERE, it LOOSENS IT: the {s_material} further material comparisons "
           f"it adds found a worse one than any of the 17 published cases did.")
    for k, j, xd in under[:6]:
        w(f"//   underflow: {k[0]} {k[1]}{k[2]} quantity {j}: single 0, double {xd:.6e}")
    if len(under) > 6:
        w(f"//   ... and {len(under)-6} more, all anomalous oxygen below 120 km")
    w("")
    w("#include <array>")
    w("#include <cstddef>")
    w("")
    w("namespace odl::atmosphere::reference {")
    w("")
    w("/// One evaluation: the nine densities, then exospheric and local temperature.")
    w("struct Record {")
    w("    char    set;        ///< 'P' a published driver case, 'S' a sweep point")
    w("    int     index;      ///< 1-based within its set")
    w("    double  gtd7[11];   ///< He O N2 O2 Ar rho H N anomO Tinf T(alt)")
    w("    double  gtd7d_rho;  ///< GTD7D's total mass density, which is NOT gtd7[5]")
    w("};")
    w("")
    w("/// The measured precision of the reference itself; the derivation is above.")
    w("/// A gate asserts these counts, not a verdict: a pass/fail over 1500")
    w("/// comparisons with one tolerance either fails on values a correct port is")
    w("/// right to produce, or passes with a tolerance that stops checking.")
    w(f"inline constexpr double kMaterialFraction     = {MATERIAL:.0e};")
    w(f"inline constexpr double kSingleMedianRelative = {med:.6e};")
    w(f"inline constexpr double kSingleWorstRelative  = {mat[0][0]:.6e};")
    w(f"inline constexpr std::size_t kClassMaterial    = {len(mat)};")
    w(f"inline constexpr std::size_t kClassImmaterial  = {len(immat)};")
    w(f"inline constexpr std::size_t kClassUnderflowed = {len(under)};")
    w(f"inline constexpr std::size_t kClassZero        = {zeros};")
    w("")
    keys = sorted(k for k in double if k[0] == "g7")
    w(f"inline constexpr std::size_t kPublishedCases = {sum(1 for k in keys if k[1]=='P')};")
    w(f"inline constexpr std::size_t kSweepCases     = {sum(1 for k in keys if k[1]=='S')};")
    w("")
    w(f"inline constexpr std::array<Record, {len(keys)}> kValues{{{{")
    for k in keys:
        v = double[k]; rho = double[("g7d", k[1], k[2])][0]
        nums = ", ".join(f"{x:.17e}" for x in v)
        w(f"    {{'{k[1]}', {k[2]:3d}, {{{nums}}}, {rho:.17e}}},")
    w("}};")
    w("")
    w("}  // namespace odl::atmosphere::reference")
    return "\n".join(L) + "\n"

if __name__ == "__main__":
    raise SystemExit(main())
